# Generated by Django 3.2.11 on 2022-02-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("commodity_code", models.CharField(max_length=10)),
                ("validity_start_date", models.DateField()),
                ("validity_end_date", models.DateField(null=True)),
                ("quantity_threshold", models.IntegerField(null=True)),
                ("sigl_product_type", models.CharField(blank=True, max_length=3, null=True)),
                ("start_datetime", models.DateTimeField(null=True)),
                ("end_datetime", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommodityGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("group_type", models.CharField(max_length=20)),
                ("group_code", models.CharField(max_length=25, unique=True)),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("group_description", models.CharField(blank=True, max_length=4000, null=True)),
                ("start_datetime", models.DateTimeField(null=True)),
                ("end_datetime", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommodityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type_code", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=4000)),
                ("status", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=30)),
                ("commission_code", models.CharField(max_length=20)),
                ("hmrc_code", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountryGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country_group_id", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=4000, unique=True)),
                ("comments", models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountryTranslationSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportApplicationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=70)),
                ("sub_type", models.CharField(blank=True, max_length=70, null=True)),
                ("licence_type_code", models.CharField(max_length=20)),
                ("sigl_flag", models.CharField(max_length=5)),
                ("chief_flag", models.CharField(max_length=5)),
                ("chief_licence_prefix", models.CharField(blank=True, max_length=10, null=True)),
                ("paper_licence_flag", models.CharField(max_length=5)),
                ("electronic_licence_flag", models.CharField(max_length=5)),
                ("cover_letter_flag", models.CharField(max_length=5)),
                ("cover_letter_schedule_flag", models.CharField(max_length=5)),
                ("category_flag", models.CharField(max_length=5)),
                ("sigl_category_prefix", models.CharField(blank=True, max_length=100, null=True)),
                ("chief_category_prefix", models.CharField(blank=True, max_length=10, null=True)),
                ("default_licence_length_months", models.IntegerField(null=True)),
                ("endorsements_flag", models.CharField(max_length=5)),
                ("default_commodity_desc", models.CharField(blank=True, max_length=200, null=True)),
                ("quantity_unlimited_flag", models.CharField(max_length=5)),
                ("unit_list_csv", models.CharField(blank=True, max_length=200, null=True)),
                ("exp_cert_upload_flag", models.CharField(max_length=5)),
                ("supporting_docs_upload_flag", models.CharField(max_length=5)),
                ("multiple_commodities_flag", models.CharField(max_length=5)),
                ("guidance_file_url", models.CharField(blank=True, max_length=4000, null=True)),
                (
                    "licence_category_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("usage_auto_category_desc_flag", models.CharField(max_length=5)),
                ("case_checklist_flag", models.CharField(max_length=5)),
                ("importer_printable", models.CharField(max_length=5)),
                ("declaration_template_mnem", models.CharField(max_length=50)),
                (
                    "commodity_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.commoditytype",
                        to_field="type_code",
                    ),
                ),
                (
                    "consignment_country_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.countrygroup",
                        to_field="country_group_id",
                    ),
                ),
                (
                    "default_commodity_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_migration.commoditygroup",
                        to_field="group_code",
                    ),
                ),
                (
                    "master_country_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.countrygroup",
                        to_field="country_group_id",
                    ),
                ),
                (
                    "origin_country_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.countrygroup",
                        to_field="country_group_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("unit_type", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=30)),
                ("hmrc_code", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("maximum_allocation", models.IntegerField(null=True)),
                (
                    "application_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.importapplicationtype",
                    ),
                ),
                (
                    "commodity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.commoditygroup",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_migration.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountryTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("translation", models.CharField(max_length=150)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.country"
                    ),
                ),
                (
                    "translation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.countrytranslationset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CountryGroupCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.country"
                    ),
                ),
                (
                    "countrygroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.countrygroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommodityGroupCommodity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.commodity"
                    ),
                ),
                (
                    "commoditygroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.commoditygroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commoditygroup",
            name="commodity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_migration.commoditytype",
                to_field="type_code",
            ),
        ),
        migrations.AddField(
            model_name="commoditygroup",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_migration.unit",
                to_field="unit_type",
            ),
        ),
        migrations.AddField(
            model_name="commodity",
            name="commodity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_migration.commoditytype",
                to_field="type_code",
            ),
        ),
    ]
