# Generated by Django 3.2.12 on 2022-03-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DFLApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("know_bought_from", models.BooleanField(null=True)),
                ("commodity_code", models.CharField(max_length=40, null=True)),
                ("commodities_xml", models.TextField(null=True)),
                ("constabulary_certs_xml", models.TextField(null=True)),
                ("fa_authorities_xml", models.TextField(null=True)),
                ("bought_from_details_xml", models.TextField(null=True)),
                ("deactivated_firearm", models.BooleanField(default=True)),
                ("proof_checked", models.BooleanField(default=False)),
                (
                    "constabulary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.constabulary",
                    ),
                ),
                (
                    "imad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.importapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DFLSupplementaryInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_datetime", models.DateTimeField(null=True)),
                ("no_report_reason", models.CharField(max_length=1000, null=True)),
                ("supplementary_report_xml", models.TextField(null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_migration.user",
                    ),
                ),
                (
                    "imad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplementary_info",
                        to="data_migration.dflapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DFLSupplementaryReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transport", models.CharField(max_length=4, null=True)),
                ("date_received", models.DateField(null=True)),
                ("bought_from_legacy_id", models.IntegerField(null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("report_firearms_xml", models.TextField(null=True)),
                (
                    "supplementary_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="data_migration.dflsupplementaryinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("filename", models.CharField(max_length=300)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
                ("path", models.CharField(max_length=4000)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="data_migration.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OILSupplementaryInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_datetime", models.DateTimeField(null=True)),
                ("no_report_reason", models.CharField(max_length=1000, null=True)),
                ("supplementary_report_xml", models.TextField(null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_migration.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OILSupplementaryReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transport", models.CharField(max_length=4, null=True)),
                ("date_received", models.DateField(null=True)),
                ("bought_from_legacy_id", models.IntegerField(null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("report_firearms_xml", models.TextField(null=True)),
                (
                    "supplementary_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="data_migration.oilsupplementaryinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TextilesApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category_licence_description", models.CharField(max_length=4000, null=True)),
                ("goods_cleared", models.CharField(max_length=5, null=True)),
                ("goods_description", models.CharField(max_length=100, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ("shipping_year", models.PositiveSmallIntegerField(null=True)),
                ("contract_files_xml", models.TextField(null=True)),
                (
                    "category_commodity_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.commoditygroup",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.commodity",
                    ),
                ),
                (
                    "imad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.importapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WoodQuotaApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("shipping_year", models.IntegerField(null=True)),
                ("exporter_name", models.CharField(max_length=100, null=True)),
                ("exporter_address", models.CharField(max_length=4000, null=True)),
                ("exporter_vat_nr", models.CharField(max_length=100, null=True)),
                ("goods_description", models.CharField(max_length=100, null=True)),
                ("goods_qty", models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ("goods_unit", models.CharField(max_length=40, null=True)),
                ("additional_comments", models.CharField(max_length=4000, null=True)),
                ("contract_files_xml", models.TextField(null=True)),
                ("export_certs_xml", models.TextField(null=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.commodity",
                    ),
                ),
                (
                    "imad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.importapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WoodQuotaChecklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_update", models.CharField(max_length=3, null=True)),
                ("fir_required", models.CharField(max_length=3, null=True)),
                ("response_preparation", models.CharField(max_length=5, null=True)),
                ("validity_period_correct", models.CharField(max_length=3, null=True)),
                ("endorsements_listed", models.CharField(max_length=3, null=True)),
                ("authorisation", models.CharField(max_length=5, null=True)),
                ("sigl_wood_application_logged", models.CharField(max_length=5, null=True)),
                (
                    "import_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist",
                        to="data_migration.woodquotaapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WoodContractFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                ("contract_date", models.DateField()),
                (
                    "file_ptr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.file"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserImportCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("imad_id", models.IntegerField()),
                ("reference", models.CharField(max_length=200)),
                ("certificate_type", models.CharField(max_length=200)),
                ("date_issued", models.DateField()),
                ("expiry_date", models.DateField()),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "constabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.constabulary",
                    ),
                ),
                (
                    "file_pkr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TextilesChecklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_update", models.CharField(max_length=3, null=True)),
                ("fir_required", models.CharField(max_length=3, null=True)),
                ("response_preparation", models.CharField(max_length=5, null=True)),
                ("validity_period_correct", models.CharField(max_length=3, null=True)),
                ("endorsements_listed", models.CharField(max_length=3, null=True)),
                ("authorisation", models.CharField(max_length=5, null=True)),
                ("within_maximum_amount_limit", models.CharField(max_length=5, null=True)),
                (
                    "import_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist",
                        to="data_migration.textilesapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpenIndividualLicenceApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("know_bought_from", models.BooleanField(null=True)),
                ("commodity_code", models.CharField(max_length=40, null=True)),
                ("commodities_xml", models.TextField(null=True)),
                ("constabulary_certs_xml", models.TextField(null=True)),
                ("fa_authorities_xml", models.TextField(null=True)),
                ("bought_from_details_xml", models.TextField(null=True)),
                ("section1", models.BooleanField(default=False)),
                ("section2", models.BooleanField(default=False)),
                (
                    "imad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.importapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OILSupplementaryReportFirearm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, null=True)),
                ("calibre", models.CharField(max_length=400, null=True)),
                ("model", models.CharField(max_length=400, null=True)),
                ("proofing", models.CharField(default=None, max_length=3, null=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("is_upload", models.BooleanField(default=False)),
                ("is_no_firearm", models.BooleanField(default=False)),
                (
                    "document",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_migration.file",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firearms",
                        to="data_migration.oilsupplementaryreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="oilsupplementaryinfo",
            name="imad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplementary_info",
                to="data_migration.openindividuallicenceapplication",
                to_field="imad_id",
            ),
        ),
        migrations.CreateModel(
            name="ImportContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("legacy_id", models.IntegerField()),
                ("entity", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("registration_number", models.CharField(max_length=200, null=True)),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("postcode", models.CharField(max_length=200, null=True)),
                ("region", models.CharField(max_length=200, null=True)),
                ("dealer", models.CharField(max_length=10, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.country",
                    ),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.importapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DFLSupplementaryReportFirearm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, null=True)),
                ("calibre", models.CharField(max_length=400, null=True)),
                ("model", models.CharField(max_length=400, null=True)),
                ("proofing", models.CharField(default=None, max_length=3, null=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("is_upload", models.BooleanField(default=False)),
                ("is_no_firearm", models.BooleanField(default=False)),
                ("goods_certificate_legacy_id", models.IntegerField()),
                (
                    "document",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="data_migration.file",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firearms",
                        to="data_migration.dflsupplementaryreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DFLGoodsCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("goods_description", models.CharField(max_length=4096)),
                ("deactivated_certificate_reference", models.CharField(max_length=50)),
                (
                    "file_pkr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.file",
                    ),
                ),
                (
                    "imad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_certificates",
                        to="data_migration.dflapplication",
                        to_field="imad_id",
                    ),
                ),
                (
                    "issuing_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="data_migration.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DFLChecklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_update", models.CharField(max_length=3, null=True)),
                ("fir_required", models.CharField(max_length=3, null=True)),
                ("response_preparation", models.CharField(max_length=5, null=True)),
                ("validity_period_correct", models.CharField(max_length=3, null=True)),
                ("endorsements_listed", models.CharField(max_length=3, null=True)),
                ("authorisation", models.CharField(max_length=5, null=True)),
                ("deactivation_certificate_attached", models.CharField(max_length=3, null=True)),
                ("deactivation_certificate_issued", models.CharField(max_length=3, null=True)),
                (
                    "import_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.dflapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChecklistFirearmsOILApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_update", models.CharField(max_length=3, null=True)),
                ("fir_required", models.CharField(max_length=3, null=True)),
                ("response_preparation", models.CharField(max_length=5, null=True)),
                ("validity_period_correct", models.CharField(max_length=3, null=True)),
                ("endorsements_listed", models.CharField(max_length=3, null=True)),
                ("authorisation", models.CharField(max_length=5, null=True)),
                ("authority_required", models.CharField(max_length=10, null=True)),
                ("authority_received", models.CharField(max_length=10, null=True)),
                ("authority_police", models.CharField(max_length=10, null=True)),
                (
                    "import_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.openindividuallicenceapplication",
                        to_field="imad_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
