# Generated by Django 4.2.11 on 2024-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0002_data_firearms_act"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="manufacturer_address_entry_type",
        ),
        migrations.RemoveField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="responsible_person_address_entry_type",
        ),
        migrations.AddField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="manufacturer_address_type",
            field=models.CharField(default="SEARCH", max_length=10),
        ),
        migrations.AddField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="responsible_address_type",
            field=models.CharField(default="SEARCH", max_length=10),
        ),
    ]
