# Generated by Django 4.2.11 on 2024-04-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0002_data_firearms_act"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateApplicationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=500)),
                ("application_type", models.CharField(max_length=3)),
                ("sharing", models.CharField(max_length=7)),
                ("created_datetime", models.DateTimeField()),
                ("last_updated_datetime", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="data_migration.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificateOfFreeSaleApplicationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("countries_xml", models.TextField(null=True)),
                ("schedules_xml", models.TextField(null=True)),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfs_template",
                        to="data_migration.certificateapplicationtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificateOfManufactureApplicationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_free_sale_uk", models.BooleanField(null=True)),
                ("is_manufacturer", models.BooleanField(null=True)),
                ("product_name", models.CharField(max_length=1000, null=True)),
                ("chemical_name", models.CharField(max_length=500, null=True)),
                ("manufacturing_process", models.TextField(max_length=4000, null=True)),
                ("countries_xml", models.TextField(null=True)),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="com_template",
                        to="data_migration.certificateapplicationtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CFSProductTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=1000)),
                ("product_type_xml", models.TextField(null=True)),
                ("active_ingredient_xml", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CFSScheduleTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("exporter_status", models.CharField(max_length=16, null=True)),
                ("brand_name_holder", models.CharField(max_length=3, null=True)),
                ("biocidal_claim", models.CharField(max_length=3, null=True)),
                ("product_eligibility", models.CharField(max_length=22, null=True)),
                ("goods_placed_on_uk_market", models.CharField(max_length=3, null=True)),
                ("goods_export_only", models.CharField(max_length=3, null=True)),
                ("any_raw_materials", models.CharField(max_length=3, null=True)),
                ("final_product_end_use", models.CharField(max_length=4000, null=True)),
                (
                    "schedule_statements_accordance_with_standards",
                    models.BooleanField(default=False),
                ),
                ("schedule_statements_is_responsible_person", models.BooleanField(default=False)),
                ("manufacturer_name", models.CharField(max_length=200, null=True)),
                ("manufacturer_address_entry_type", models.CharField(max_length=10)),
                ("manufacturer_postcode", models.CharField(max_length=30, null=True)),
                ("manufacturer_address", models.CharField(max_length=4000, null=True)),
                ("product_xml", models.TextField(null=True)),
                ("legislation_xml", models.TextField(null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="data_migration.certificateoffreesaleapplicationtemplate",
                    ),
                ),
                (
                    "country_of_manufacture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data_migration.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cfsschedule",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="exportapplicationcertificate",
            name="updated_at",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="COMTemplateCountries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "certificateofmanufactureapplicationtemplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.certificateofmanufactureapplicationtemplate",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.country"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CFSTemplateLegislation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cfsschedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.cfsscheduletemplate",
                    ),
                ),
                (
                    "productlegislation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.productlegislation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CFSTemplateCountries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "certificateoffreesaleapplicationtemplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_migration.certificateoffreesaleapplicationtemplate",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.country"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CFSProductTypeTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_type_number", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_type_numbers",
                        to="data_migration.cfsproducttemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cfsproducttemplate",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="data_migration.cfsscheduletemplate",
            ),
        ),
        migrations.CreateModel(
            name="CFSProductActiveIngredientTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("cas_number", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_ingredients",
                        to="data_migration.cfsproducttemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
