# Generated by Django 4.2.11 on 2024-05-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0004_remove_autonow_add_revoke_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="file_folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gmp",
                to="data_migration.filefolder",
            ),
        ),
    ]
