# Generated by Django 4.2.11 on 2024-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_migration",
            "0005_alter_certificateofgoodmanufacturingpracticeapplication_file_folder",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="importapplication",
            name="last_update_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
