# Generated by Django 4.2.13 on 2024-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0006_alter_importapplication_last_update_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="silgoodssection5",
            old_name="section_5_clause",
            new_name="section_5_code",
        ),
    ]
