# Generated by Django 4.2.13 on 2024-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0008_exporter_exclusive_correspondence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dflsupplementaryreport",
            name="created",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="oilsupplementaryreport",
            name="created",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="silsupplementaryreport",
            name="created",
            field=models.DateTimeField(null=True),
        ),
    ]
