# Generated by Django 4.2.16 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0014_dflgoodscertificate_goods_description_original"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionsandadhocapplication",
            name="commodities_response_xml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount_original",
            field=models.DecimalField(decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value_original",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount",
            field=models.DecimalField(decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
