# Generated by Django 4.2.16 on 2024-09-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0015_sanctions_case_officer_goods_edits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="template",
            name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="template",
            name="template_content",
        ),
        migrations.RemoveField(
            model_name="template",
            name="template_title",
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(null=True)),
                ("is_active", models.BooleanField()),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=4000, null=True)),
                ("content", models.TextField(null=True)),
                ("template_type", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="data_migration.user"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_migration.template"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
