# Generated by Django 4.2.16 on 2024-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migration", "0016_template_versioning"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequestFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("access_request_id", models.IntegerField(null=True)),
                ("filename", models.CharField(max_length=300)),
                ("content_type", models.CharField(max_length=100, null=True)),
                ("file_size", models.IntegerField()),
                ("path", models.CharField(max_length=4000)),
                ("created_datetime", models.DateTimeField()),
                ("created_by_id", models.IntegerField(null=True)),
                ("rfi_id", models.IntegerField(null=True)),
                ("secondary_data_uref", models.CharField(max_length=20, null=True)),
                ("fir_xml", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
