# Generated by Django 2.1.7 on 2019-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
