# Generated by Django 2.1.7 on 2019-04-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('web', '0002_auto_20190410_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('IMPORTER', 'Request access to act as an Importer'), ('IMPORTER_AGENT', 'Request access to act as an Agent for an Importer'), ('EXPORTER', 'Request access to act as an Exporter'), ('EXPORTER_AGENT', 'Request access to act as an Agent for an Exporter')], max_length=30)),
                ('organisation_name', models.CharField(max_length=100)),
                ('organisation_address', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_address', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='web.User')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequestProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AccessRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
