# Generated by Django 2.1.7 on 2019-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_accessrequest_accessrequestprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_complete',
            field=models.BooleanField(default=False),
        ),
    ]
