export_case_note_1 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>1</NOTE_ID>
    <STATUS>DRAFT</STATUS>
    <BODY>This is a case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>1</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>4</NOTE_ID>
    <STATUS>DELETED</STATUS>
    <BODY>This is a deleted case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>4</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""


export_case_note_2 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>2</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is another case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>2</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>3</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is a third case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>3</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""


export_fir_xml_1 = """
<RFI_LIST>
  <RFI>
    <RFI_ID>1</RFI_ID>
    <CASE_RFI_REFERENCE>1</CASE_RFI_REFERENCE>
    <STATUS>CLOSED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>abc</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2022-09-21T08:31:34</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <RESPONSE_DETAILS>response</RESPONSE_DETAILS>
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME>2022-09-21T08:31:34</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </RFI>
</RFI_LIST>
"""


export_fir_xml_2 = """
<RFI_LIST>
  <RFI>
    <RFI_ID>2</RFI_ID>
    <CASE_RFI_REFERENCE>1</CASE_RFI_REFERENCE>
    <STATUS>DELETED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME />
      <REQUESTED_BY_WUA_ID />
      <SUBJECT />
      <CC_EMAIL_LIST/>
      <BODY />
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME>2022-09-21T08:31:34</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
  </RFI>
  <RFI>
    <RFI_ID>3</RFI_ID>
    <CASE_RFI_REFERENCE>2</CASE_RFI_REFERENCE>
    <STATUS>OPEN</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>ab; cd</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </RFI>
</RFI_LIST>
"""


export_update_xml_1 = """
<UPDATE_LIST>
  <UPDATE>
    <UPDATE_ID>1</UPDATE_ID>
    <STATUS>CLOSED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>abc</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2022-09-21T08:31:34</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <RESPONSE_DETAILS>response</RESPONSE_DETAILS>
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME>2022-09-21T08:31:34</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </UPDATE>
</UPDATE_LIST>
"""


export_update_xml_2 = """
<UPDATE_LIST>
  <UPDATE>
    <UPDATE_ID>2</UPDATE_ID>
    <STATUS>DELETED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME />
      <REQUESTED_BY_WUA_ID />
      <SUBJECT />
      <CC_EMAIL_LIST/>
      <BODY />
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME>2022-09-21T08:31:34</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
  </UPDATE>
  <UPDATE>
    <UPDATE_ID>3</UPDATE_ID>
    <STATUS>OPEN</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>ab; cd</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </UPDATE>
</UPDATE_LIST>
"""
