export_case_note_1 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>1</NOTE_ID>
    <STATUS>DRAFT</STATUS>
    <BODY>This is a case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>1</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>4</NOTE_ID>
    <STATUS>DELETED</STATUS>
    <BODY>This is a deleted case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>4</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""


export_case_note_2 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>2</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is another case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>2</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>3</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is a third case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>3</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""


export_fir_xml_1 = """
<RFI_LIST>
  <RFI>
    <RFI_ID>1</RFI_ID>
    <CASE_RFI_REFERENCE>1</CASE_RFI_REFERENCE>
    <STATUS>CLOSED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>abc</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2022-09-21T08:31:34</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <RESPONSE_DETAILS>Further Information Request Data</RESPONSE_DETAILS>
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME>2022-09-21T08:31:34</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </RFI>
</RFI_LIST>
"""


export_fir_xml_2 = """
<RFI_LIST>
  <RFI>
    <RFI_ID>2</RFI_ID>
    <CASE_RFI_REFERENCE>1</CASE_RFI_REFERENCE>
    <STATUS>DELETED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME />
      <REQUESTED_BY_WUA_ID />
      <SUBJECT />
      <CC_EMAIL_LIST/>
      <BODY />
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME>2022-09-21T08:31:34</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
  </RFI>
  <RFI>
    <RFI_ID>3</RFI_ID>
    <CASE_RFI_REFERENCE>2</CASE_RFI_REFERENCE>
    <STATUS>OPEN</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>ab; cd</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </RFI>
</RFI_LIST>
"""


export_update_xml_1 = """
<UPDATE_LIST>
  <UPDATE>
    <UPDATE_ID>1</UPDATE_ID>
    <STATUS>CLOSED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>abc</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2022-09-21T08:31:34</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <SUMMARY_OF_CHANGES>update request response info</SUMMARY_OF_CHANGES>
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME>2022-09-21T08:31:34</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </UPDATE>
</UPDATE_LIST>
"""


export_update_xml_2 = """
<UPDATE_LIST>
  <UPDATE>
    <UPDATE_ID>2</UPDATE_ID>
    <STATUS>DELETED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME />
      <REQUESTED_BY_WUA_ID />
      <SUBJECT />
      <CC_EMAIL_LIST/>
      <BODY />
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <SUMMARY_OF_CHANGES />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME>2022-09-21T08:31:34</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
  </UPDATE>
  <UPDATE>
    <UPDATE_ID>3</UPDATE_ID>
    <STATUS>OPEN</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2022-09-21T08:31:34</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <SUBJECT>Subject</SUBJECT>
      <CC_EMAIL_LIST>ab; cd</CC_EMAIL_LIST>
      <BODY>body</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <RESPONSE_DETAILS />
    </RESPONSE>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <WITHDRAW_LIST/>
  </UPDATE>
</UPDATE_LIST>
"""


import_withdrawal = """
<WITHDRAW_LIST>
  <WITHDRAW>
    <WITHDRAW_STATUS>DELETED</WITHDRAW_STATUS>
    <WITHDRAW_REASON>First reason</WITHDRAW_REASON>
    <WITHDRAW_REQUESTER_WUA>2</WITHDRAW_REQUESTER_WUA>
    <WITHDRAW_REQUESTED_DATE>2024-02-01</WITHDRAW_REQUESTED_DATE>
    <WITHDRAW_DECISION />
    <WITHDRAW_REJECT_REASON />
    <WITHDRAW_RESPONDER_WUA />
    <WITHDRAW_RESPONDED_DATE />
  </WITHDRAW>
  <WITHDRAW>
    <WITHDRAW_STATUS>REJECTED</WITHDRAW_STATUS>
    <WITHDRAW_REASON>Second reason</WITHDRAW_REASON>
    <WITHDRAW_REQUESTER_WUA>2</WITHDRAW_REQUESTER_WUA>
    <WITHDRAW_REQUESTED_DATE>2024-02-02</WITHDRAW_REQUESTED_DATE>
    <WITHDRAW_DECISION>REJECTED</WITHDRAW_DECISION>
    <WITHDRAW_REJECT_REASON>Rejection Reason</WITHDRAW_REJECT_REASON>
    <WITHDRAW_RESPONDER_WUA>2</WITHDRAW_RESPONDER_WUA>
    <WITHDRAW_RESPONDED_DATE>2024-02-03</WITHDRAW_RESPONDED_DATE>
  </WITHDRAW>
  <WITHDRAW>
    <WITHDRAW_STATUS>ACCEPTED</WITHDRAW_STATUS>
    <WITHDRAW_REASON>Third reason</WITHDRAW_REASON>
    <WITHDRAW_REQUESTER_WUA>2</WITHDRAW_REQUESTER_WUA>
    <WITHDRAW_REQUESTED_DATE>2024-02-02</WITHDRAW_REQUESTED_DATE>
    <WITHDRAW_DECISION>ACCEPTED</WITHDRAW_DECISION>
    <WITHDRAW_REJECT_REASON />
    <WITHDRAW_RESPONDER_WUA>2</WITHDRAW_RESPONDER_WUA>
    <WITHDRAW_RESPONDED_DATE>2024-02-02</WITHDRAW_RESPONDED_DATE>
  </WITHDRAW>
  <WITHDRAW>
    <WITHDRAW_STATUS>DRAFT</WITHDRAW_STATUS>
    <WITHDRAW_REASON>Draft reason</WITHDRAW_REASON>
    <WITHDRAW_REQUESTER_WUA>2</WITHDRAW_REQUESTER_WUA>
    <WITHDRAW_REQUESTED_DATE>2024-02-02</WITHDRAW_REQUESTED_DATE>
    <WITHDRAW_DECISION />
    <WITHDRAW_REJECT_REASON />
    <WITHDRAW_RESPONDER_WUA />
    <WITHDRAW_RESPONDED_DATE />
  </WITHDRAW>
</WITHDRAW_LIST>
"""


export_withdrawal = """
<WITHDRAWAL_LIST>
  <WITHDRAWAL>
    <WITHDRAWAL_ID>1</WITHDRAWAL_ID>
    <STATUS>DELETED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2024-01-31T11:27:36</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <BODY>First reason</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <DECISION />
      <REJECT_REASON />
    </RESPONSE>
    <DELETE>
      <DELETED_DATETIME>2024-01-31T12:27:36</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
    <RETRACT_LIST />
  </WITHDRAWAL>
  <WITHDRAWAL>
    <WITHDRAWAL_ID>2</WITHDRAWAL_ID>
    <STATUS>REJECTED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2024-01-31T13:37:36</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <BODY>Second reason</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2024-01-31T13:40:00</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <DECISION>REJECTED</DECISION>
      <REJECT_REASON>Reject Reason</REJECT_REASON>
    </RESPONSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <RETRACT_LIST />
  </WITHDRAWAL>
  <WITHDRAWAL>
    <WITHDRAWAL_ID>3</WITHDRAWAL_ID>
    <STATUS>ACCEPTED</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2024-01-31T15:00:00</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <BODY>Third reason</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME>2024-01-31T15:10:00</RESPONDED_DATETIME>
      <RESPONDED_BY_WUA_ID>2</RESPONDED_BY_WUA_ID>
      <DECISION>ACCEPTED</DECISION>
      <REJECT_REASON />
    </RESPONSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <RETRACT_LIST />
  </WITHDRAWAL>
  <WITHDRAWAL>
    <WITHDRAWAL_ID>4</WITHDRAWAL_ID>
    <STATUS>DRAFT</STATUS>
    <REQUEST>
      <REQUESTED_DATETIME>2024-01-31T11:27:36</REQUESTED_DATETIME>
      <REQUESTED_BY_WUA_ID>2</REQUESTED_BY_WUA_ID>
      <BODY>Draft reason</BODY>
    </REQUEST>
    <RESPONSE>
      <RESPONDED_DATETIME />
      <RESPONDED_BY_WUA_ID />
      <DECISION />
      <REJECT_REASON />
    </RESPONSE>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
    <RETRACT_LIST />
  </WITHDRAWAL>
</WITHDRAWAL_LIST>
"""


condtabulary_email_attachments = """
<FIREARMS_CERTIFICATE_LIST>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1100</TARGET_ID>
    <SELECT_FLAG>true</SELECT_FLAG>
  </FIREARMS_CERTIFICATE>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1101</TARGET_ID>
    <SELECT_FLAG>true</SELECT_FLAG>
  </FIREARMS_CERTIFICATE>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1103</TARGET_ID>
    <SELECT_FLAG>true</SELECT_FLAG>
  </FIREARMS_CERTIFICATE>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1200</TARGET_ID>
    <SELECT_FLAG>false</SELECT_FLAG>
  </FIREARMS_CERTIFICATE>
</FIREARMS_CERTIFICATE_LIST>
"""
