from .cfs import cfs_product, cfs_product_biocide

cat_countries_xml = """
<COUNTRIES>
  <COUNTRY_LIST>
    <COUNTRY>1</COUNTRY>
    <COUNTRY>2</COUNTRY>
  </COUNTRY_LIST>
</COUNTRIES>
"""


cfs_schedule_template_xml = f"""
<SCHEDULE_LIST>
  <SCHEDULE>
    <IS_DOMESTIC_MARKET_PESTICIDE />
    <IS_PESTICIDE_MANUFACTURER />
    <MANUFACTURER_STATUS>IS_MANUFACTURER</MANUFACTURER_STATUS>
    <BRAND_NAME_STATUS>true</BRAND_NAME_STATUS>
    <LEGISLATION_LIST>
      <LEGISLATION>1</LEGISLATION>
      <LEGISLATION>3</LEGISLATION>
    </LEGISLATION_LIST>
    <BIOCIDAL_CLAIMS>false</BIOCIDAL_CLAIMS>
    <ELIGIBILITY>MAY_BE_SOLD</ELIGIBILITY>
    <IS_EU_MARKET>true</IS_EU_MARKET>
    <IS_NEVER_EU_MARKET>false</IS_NEVER_EU_MARKET>
    <RAW_MATERIALS_EXIST>true</RAW_MATERIALS_EXIST>
    <END_USE>Test End Use</END_USE>
    <COUNTRY_OF_MANUFACTURE>1</COUNTRY_OF_MANUFACTURE>
    <STATEMENT_LIST>
      <STATEMENT>EU_COSMETICS_RESPONSIBLE_PERSON</STATEMENT>
    </STATEMENT_LIST>
    <MANUFACTURED_AT>
      <INCLUDE_ON_SCHEDULE>true</INCLUDE_ON_SCHEDULE>
      <NAME>Test Manufacturer</NAME>
      <ADDRESS_ENTRY_TYPE>SEARCH</ADDRESS_ENTRY_TYPE>
      <POSTCODE>Test Postcode</POSTCODE>
      <ADDRESS>Test Address</ADDRESS>
    </MANUFACTURED_AT>
    {cfs_product}
  </SCHEDULE>
  <SCHEDULE>
    <IS_DOMESTIC_MARKET_PESTICIDE />
    <IS_PESTICIDE_MANUFACTURER />
    <MANUFACTURER_STATUS>IS_NOT_MANUFACTURER</MANUFACTURER_STATUS>
    <BRAND_NAME_STATUS>false</BRAND_NAME_STATUS>
    <LEGISLATION_LIST>
      <LEGISLATION>2</LEGISLATION>
    </LEGISLATION_LIST>
    <BIOCIDAL_CLAIMS>true</BIOCIDAL_CLAIMS>
    <ELIGIBILITY>ON_SALE</ELIGIBILITY>
    <IS_EU_MARKET>false</IS_EU_MARKET>
    <IS_NEVER_EU_MARKET>true</IS_NEVER_EU_MARKET>
    <RAW_MATERIALS_EXIST>false</RAW_MATERIALS_EXIST>
    <END_USE />
    <COUNTRY_OF_MANUFACTURE>1</COUNTRY_OF_MANUFACTURE>
    <STATEMENT_LIST>
      <STATEMENT>GOOD_MANUFACTURING_PRACTICE</STATEMENT>
    </STATEMENT_LIST>
    <MANUFACTURED_AT>
      <INCLUDE_ON_SCHEDULE>true</INCLUDE_ON_SCHEDULE>
      <NAME>Test Manufacturer</NAME>
      <ADDRESS_ENTRY_TYPE>MANUAL</ADDRESS_ENTRY_TYPE>
      <POSTCODE>Test Postcode</POSTCODE>
      <ADDRESS>Test Address</ADDRESS>
    </MANUFACTURED_AT>
    {cfs_product_biocide}
  </SCHEDULE>
</SCHEDULE_LIST>
"""
