# flake8: noqa
import_contact_xml = """
<SELLER_HOLDER_LIST>
  <SELLER_HOLDER>
    <PERSON_DETAILS>
      <PERSON_TYPE>LEGAL_PERSON</PERSON_TYPE>
      <LEGAL_PERSON_NAME>FIREARMS DEALER</LEGAL_PERSON_NAME>
      <REGISTRATION_NUMBER />
      <FIRST_NAME />
      <SURNAME />
    </PERSON_DETAILS>
    <ADDRESS>
      <STREET_AND_NUMBER>123 FAKE ST</STREET_AND_NUMBER>
      <TOWN_CITY>FAKE CITY</TOWN_CITY>
      <POSTCODE />
      <REGION>FAKE REGION</REGION>
      <COUNTRY>1</COUNTRY>
    </ADDRESS>
    <IS_DEALER_FLAG>Y</IS_DEALER_FLAG>
    <SELLER_HOLDER_ID>1</SELLER_HOLDER_ID>
    <UPDATE_FLAG />
  </SELLER_HOLDER>
  <SELLER_HOLDER>
    <PERSON_DETAILS>
      <PERSON_TYPE>LEGAL_PERSON</PERSON_TYPE>
      <LEGAL_PERSON_NAME>ANOTHER DELEAR</LEGAL_PERSON_NAME>
      <REGISTRATION_NUMBER />
      <FIRST_NAME />
      <SURNAME />
    </PERSON_DETAILS>
    <ADDRESS>
      <STREET_AND_NUMBER>456 FAKE RD</STREET_AND_NUMBER>
      <TOWN_CITY>FAKE TOWN</TOWN_CITY>
      <POSTCODE />
      <REGION>SOUTH FAKE REGION</REGION>
      <COUNTRY>1</COUNTRY>
    </ADDRESS>
    <IS_DEALER_FLAG>Y</IS_DEALER_FLAG>
    <SELLER_HOLDER_ID>2</SELLER_HOLDER_ID>
    <UPDATE_FLAG />
  </SELLER_HOLDER>
</SELLER_HOLDER_LIST>
""".strip()

sr_upload_goods_template = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-10, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-10, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.{}</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>UPLOAD</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST/>
    <FILE_UPLOAD_LIST>
      <FILE_UPLOAD>
          <FILE_CONTENT>
            <filename>SR Upload.pdf</filename>
            <content-type>pdf</content-type>
            <size>1234</size>
            <upload-date-time>2022-11-05T12:11:04</upload-date-time>
            <file-id>abcde</file-id>
          </FILE_CONTENT>
      </FILE_UPLOAD>
    </FILE_UPLOAD_LIST>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()

sr_upload_goods = sr_upload_goods_template.format(1)

sr_upload_xml = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <HISTORICAL_REPORT_LIST>
      <HISTORICAL_REPORT>
        <HISTORICAL_REPORT_DETAILS>
          <GOODS_LINE_LIST>
            <GOODS_LINE>
              <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
              <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
              <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
              <FA_REPORTING_MODE>UPLOAD</FA_REPORTING_MODE>
              <FIREARMS_DETAILS_LIST/>
              <FILE_UPLOAD_LIST>
                <FILE_UPLOAD>
                    <FILE_CONTENT>
                      <filename>SR Upload.pdf</filename>
                      <content-type>pdf</content-type>
                      <size>1234</size>
                      <upload-date-time>2022-11-05T11:11:03</upload-date-time>
                      <file-id>defghe</file-id>
                    </FILE_CONTENT>
                </FILE_UPLOAD>
              </FILE_UPLOAD_LIST>
              <GOODS_ITEM_SUBMIT/>
            </GOODS_LINE>
          </GOODS_LINE_LIST>
        </HISTORICAL_REPORT_DETAILS>
      </HISTORICAL_REPORT>
    </HISTORICAL_REPORT_LIST>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      {}
      <MODE_OF_TRANSPORT>AIR</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-10-14</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-08T08:31:34</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip().format(
    sr_upload_goods_template.format(1)
)


sr_manual_goods_1 = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-1, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>50</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-1, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>N/A</SERIAL_NUMBER>
        <CALIBRE>6MM</CALIBRE>
        <MAKE_MODEL>A gun barrel</MAKE_MODEL>
        <PROOFING>N</PROOFING>
      </FIREARMS_DETAILS>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>123456</SERIAL_NUMBER>
        <CALIBRE>.30</CALIBRE>
        <MAKE_MODEL>A gun</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()

sr_manual_goods_2 = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-2, component parts</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-2, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.2</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
        <CALIBRE>mixed</CALIBRE>
        <MAKE_MODEL>Various</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()


sr_manual_goods_3_template = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-3, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>50</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-3, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.{}</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>321</SERIAL_NUMBER>
        <CALIBRE>100</CALIBRE>
        <MAKE_MODEL>Test A</MAKE_MODEL>
        <PROOFING>N</PROOFING>
      </FIREARMS_DETAILS>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>543</SERIAL_NUMBER>
        <CALIBRE>55</CALIBRE>
        <MAKE_MODEL>Test B</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-4, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-4, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.{}</GOOD_ITEM_ID>
    <FA_REPORTING_MODE />
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>11</SERIAL_NUMBER>
        <CALIBRE>120</CALIBRE>
        <MAKE_MODEL>Test C</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()

sr_manual_goods_3 = sr_manual_goods_3_template.format(3, 4)

sr_manual_goods_4 = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-2, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>50</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-2, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.2</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>321</SERIAL_NUMBER>
        <CALIBRE>100</CALIBRE>
        <MAKE_MODEL>Test B</MAKE_MODEL>
        <PROOFING>N</PROOFING>
      </FIREARMS_DETAILS>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>543</SERIAL_NUMBER>
        <CALIBRE>55</CALIBRE>
        <MAKE_MODEL>Test A</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-1, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-1, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
    <FA_REPORTING_MODE />
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>11</SERIAL_NUMBER>
        <CALIBRE>120</CALIBRE>
        <MAKE_MODEL>Test C</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()

sr_manual_goods_5 = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Firearms-5, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>50</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Firearms-5, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.5</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>N/A</SERIAL_NUMBER>
        <CALIBRE>6MM</CALIBRE>
        <MAKE_MODEL>A gun barrel</MAKE_MODEL>
        <PROOFING>N</PROOFING>
      </FIREARMS_DETAILS>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>123456</SERIAL_NUMBER>
        <CALIBRE>.30</CALIBRE>
        <MAKE_MODEL>A gun</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
""".strip()


sr_manual_legacy_goods = """
<GOODS_LINE_LIST>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Legacy Commodity</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>25</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Legacy Commodity1</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
        <CALIBRE>mixed</CALIBRE>
        <MAKE_MODEL>Various</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
  <GOODS_LINE>
    <GOODS_ITEM_DESC>Legacy Commodity OC</GOODS_ITEM_DESC>
    <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
    <GOOD_ITEM_ID>Legacy Commodity OC2</GOOD_ITEM_ID>
    <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
    <FIREARMS_DETAILS_LIST>
      <FIREARMS_DETAILS>
        <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
        <CALIBRE>999</CALIBRE>
        <MAKE_MODEL>Firearm</MAKE_MODEL>
        <PROOFING>Y</PROOFING>
      </FIREARMS_DETAILS>
    </FIREARMS_DETAILS_LIST>
    <FILE_UPLOAD_LIST/>
    <GOODS_ITEM_SUBMIT/>
  </GOODS_LINE>
</GOODS_LINE_LIST>
"""

sr_manual_xml = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      {0}
      <MODE_OF_TRANSPORT>RAIL</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-11-03</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-07T13:41:00</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
  <FA_SUPPLEMENTARY_REPORT>
    <HISTORICAL_REPORT_LIST/>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      {1}
      <MODE_OF_TRANSPORT/>
      <RECEIVED_DATE/>
      <REPORT_SELLER_HOLDER/>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-12-20T10:24:30</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip().format(
    sr_manual_goods_1, sr_manual_goods_2
)


sr_manual_xml_5_goods = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      {0}
      {1}
      {2}
      {3}
      <MODE_OF_TRANSPORT>RAIL</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-11-03</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-07T13:41:00</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip().format(
    sr_manual_goods_1.rstrip("</GOODS_LINE_LIST>").strip(),
    sr_manual_goods_2.lstrip("<GOODS_LINE_LIST>").rstrip("</GOODS_LINE_LIST>").strip(),
    sr_manual_goods_3_template.format(3, 4)
    .lstrip("<GOODS_LINE_LIST>")
    .rstrip("</GOODS_LINE_LIST>")
    .strip(),
    sr_manual_goods_5.lstrip("<GOODS_LINE_LIST>").strip(),
)


sr_manual_xml_legacy = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      {0}
      <MODE_OF_TRANSPORT>RAIL</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-11-03</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-07T13:41:00</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip().format(
    sr_manual_legacy_goods
)


sr_list = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
      <HISTORICAL_REPORT_LIST/>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
              <CALIBRE>mixed</CALIBRE>
              <MAKE_MODEL>Various</MAKE_MODEL>
              <PROOFING>Y</PROOFING>
            </FIREARMS_DETAILS>
          </FIREARMS_DETAILS_LIST>
          <FILE_UPLOAD_LIST/>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT/>
      <RECEIVED_DATE/>
      <REPORT_SELLER_HOLDER/>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>1</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-12-20T10:24:30</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip()

dfl_sr = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <HISTORICAL_REPORT_LIST>
      <HISTORICAL_REPORT>
        <HISTORICAL_REPORT_DETAILS>
          <GOODS_LINE_LIST>
            <GOODS_LINE>
              <GOODS_ITEM_DESC>Test Commodity A</GOODS_ITEM_DESC>
              <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
              <GOOD_ITEM_ID>Test Commodity A1</GOOD_ITEM_ID>
              <FA_REPORTING_MODE>UPLOAD</FA_REPORTING_MODE>
              <FIREARMS_DETAILS_LIST/>
              <FILE_UPLOAD_LIST>
                <FILE_UPLOAD>
                    <FILE_CONTENT>
                      <filename>SR Upload.pdf</filename>
                      <content-type>pdf</content-type>
                      <size>1234</size>
                      <upload-date-time>2022-11-05T11:11:03</upload-date-time>
                      <file-id>defghe</file-id>
                    </FILE_CONTENT>
                </FILE_UPLOAD>
              </FILE_UPLOAD_LIST>
              <GOODS_ITEM_SUBMIT/>
            </GOODS_LINE>
          </GOODS_LINE_LIST>
        </HISTORICAL_REPORT_DETAILS>
      </HISTORICAL_REPORT>
    </HISTORICAL_REPORT_LIST>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Test Commodity A</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Test Commodity A1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>UPLOAD</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST/>
          <FILE_UPLOAD_LIST>
            <FILE_UPLOAD>
                <FILE_CONTENT>
                  <filename>SR Upload.pdf</filename>
                  <content-type>pdf</content-type>
                  <size>1234</size>
                  <upload-date-time>2022-11-05T12:11:03</upload-date-time>
                  <file-id>abcde</file-id>
                </FILE_CONTENT>
            </FILE_UPLOAD>
          </FILE_UPLOAD_LIST>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Test Commodity B</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>25</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Test Commodity B2</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
              <CALIBRE>mixed</CALIBRE>
              <MAKE_MODEL>Various</MAKE_MODEL>
              <PROOFING>Y</PROOFING>
            </FIREARMS_DETAILS>
          </FIREARMS_DETAILS_LIST>
          <FILE_UPLOAD_LIST/>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT>AIR</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-10-14</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-08T08:31:34</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
"""

dfl_goods_cert = """
<FA_GOODS_CERTS>
  <COMMODITY_LIST>
    <COMMODITY>
      <COMMODITY_DESC>Test Commodity A</COMMODITY_DESC>
      <OBSOLETE_CALIBRE />
      <QUANTITY>1</QUANTITY>
      <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
      <QUANTITY_UNLIMITED_FLAG />
      <UNIT>UNITS</UNIT>
    </COMMODITY>
    <COMMODITY>
      <COMMODITY_DESC>Test Commodity B</COMMODITY_DESC>
      <OBSOLETE_CALIBRE />
      <QUANTITY>1</QUANTITY>
      <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
      <QUANTITY_UNLIMITED_FLAG />
      <UNIT>UNITS</UNIT>
    </COMMODITY>
  </COMMODITY_LIST>
  <FIREARMS_CERTIFICATE_LIST>
    <FIREARMS_CERTIFICATE>
      <TARGET_ID>5000</TARGET_ID>
      <CERTIFICATE_REF>REF A</CERTIFICATE_REF>
      <CERTIFICATE_TYPE>DEACTIVATED</CERTIFICATE_TYPE>
      <CONSTABULARY />
      <DATE_ISSUED />
      <EXPIRY_DATE />
      <ISSUING_COUNTRY>1</ISSUING_COUNTRY>
    </FIREARMS_CERTIFICATE>
    <FIREARMS_CERTIFICATE>
      <TARGET_ID>5001</TARGET_ID>
      <CERTIFICATE_REF>REF B</CERTIFICATE_REF>
      <CERTIFICATE_TYPE>DEACTIVATED</CERTIFICATE_TYPE>
      <CONSTABULARY />
      <DATE_ISSUED />
      <EXPIRY_DATE />
      <ISSUING_COUNTRY>2</ISSUING_COUNTRY>
    </FIREARMS_CERTIFICATE>
  </FIREARMS_CERTIFICATE_LIST>
</FA_GOODS_CERTS>
""".strip()

rfd_cert = """
<FIREARMS_CERTIFICATE_LIST>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1</TARGET_ID>
    <CERTIFICATE_REF>A REF</CERTIFICATE_REF>
    <CERTIFICATE_TYPE>RFD</CERTIFICATE_TYPE>
    <CONSTABULARY>1</CONSTABULARY>
    <DATE_ISSUED>2020-06-08</DATE_ISSUED>
    <EXPIRY_DATE>2023-06-07</EXPIRY_DATE>
    <ISSUING_COUNTRY />
  </FIREARMS_CERTIFICATE>
""".strip()


sil_goods = """
<COMMODITY_LIST>
  <COMMODITY>
    <SECTION>SEC1</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Gun</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>5</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC2</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Rifle</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY></QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>true</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC5</SECTION>
    <SECTION_5_CLAUSE>5_1_ABA</SECTION_5_CLAUSE>
    <COMMODITY_DESC>Test Pistol</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>10</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OBSOLETE_CALIBRE</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Revolver</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID>444</OC_ID>
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>1</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG />
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900 />
    <CURIOSITY_OR_ORNAMENT>Y</CURIOSITY_OR_ORNAMENT>
    <CURIOSITY_STATEMENT_AGREED>true</CURIOSITY_STATEMENT_AGREED>
    <BREECH_LOADING_CENTREFIRE>Y</BREECH_LOADING_CENTREFIRE>
    <MANUFACTURED_AFTER_1899_BEFORE_1939>Y</MANUFACTURED_AFTER_1899_BEFORE_1939>
    <ORIGINAL_CHAMBERING>Y</ORIGINAL_CHAMBERING>
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OTHER</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Other</COMMODITY_DESC>
    <QUANTITY>1</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG />
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900 />
    <CURIOSITY_OR_ORNAMENT>Y</CURIOSITY_OR_ORNAMENT>
    <CURIOSITY_STATEMENT_AGREED>true</CURIOSITY_STATEMENT_AGREED>
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939>Y</MANUFACTURED_AFTER_1899_BEFORE_1939>
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING>N</MUZZLE_LOADING>
    <OTHER_BREECH_RIMFIRE_CARTRIDGE>Y</OTHER_BREECH_RIMFIRE_CARTRIDGE>
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED>.32 rimfire</OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED>
    <OTHER_IGNITION_SYSTEM>N</OTHER_IGNITION_SYSTEM>
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES>N</SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES>
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE>N</SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE>
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT>1.0</S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
  </COMMODITY>
</COMMODITY_LIST>
""".strip()


sil_response_goods = """
<COMMODITY_LIST>
  <COMMODITY>
    <SECTION>SEC1</SECTION>
    <COMMODITY_DESC>Test Gun Override</COMMODITY_DESC>
    <QUANTITY>17</QUANTITY>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC2</SECTION>
    <COMMODITY_DESC></COMMODITY_DESC>
    <QUANTITY></QUANTITY>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC5</SECTION>
    <COMMODITY_DESC>Test Pistol</COMMODITY_DESC>
    <QUANTITY>10</QUANTITY>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OBSOLETE_CALIBRE</SECTION>
    <COMMODITY_DESC>Test Revolver Override</COMMODITY_DESC>
    <QUANTITY>1</QUANTITY>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OTHER</SECTION>
    <COMMODITY_DESC>Test Other</COMMODITY_DESC>
    <QUANTITY>100</QUANTITY>
  </COMMODITY>
</COMMODITY_LIST>
""".strip()


sil_goods_sec_1 = """
<COMMODITY_LIST>
  <COMMODITY>
    <SECTION>SEC1</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Gun</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>5</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
</COMMODITY_LIST>
"""

sil_goods_legacy = """
<COMMODITY_LIST>
  <COMMODITY>
    <COMMODITY_DESC>Legacy Commodity</COMMODITY_DESC>
    <QUANTITY>25</QUANTITY>
    <QUANTITY_UNLIMITED />
    <QUANTITY_UNLIMITED_FLAG />
    <UNIT />
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <OC_ID_ERROR />
      <NA_FLAG />
    </OBSOLETE_CALIBRE>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_DESC>Legacy Commodity OC</COMMODITY_DESC>
    <QUANTITY />
    <QUANTITY_UNLIMITED />
    <QUANTITY_UNLIMITED_FLAG>true</QUANTITY_UNLIMITED_FLAG>
    <UNIT />
    <OBSOLETE_CALIBRE>
      <OC_ID>444</OC_ID>
      <OC_ID_ERROR />
      <NA_FLAG />
    </OBSOLETE_CALIBRE>
  </COMMODITY>
</COMMODITY_LIST>
"""

authority_ids = """
<AUTHORITY_LIST>
  <AUTHORITY>
    <IA_ID />
    <SELECTED />
  </AUTHORITY>
  <AUTHORITY>
    <IA_ID>123</IA_ID>
    <SELECTED>true</SELECTED>
  </AUTHORITY>
  <AUTHORITY>
    <IA_ID>456</IA_ID>
    <SELECTED>true</SELECTED>
  </AUTHORITY>
  <AUTHORITY>
    <IA_ID>789</IA_ID>
    <SELECTED>false</SELECTED>
  </AUTHORITY>
</AUTHORITY_LIST>
"""

quantity_list = """
<GOODS_CATEGORY_LIST>
  <GOODS_CATEGORY>
    <CATEGORY_ID>1</CATEGORY_ID>
    <QUANTITY_WRAPPER>
      <QUANTITY>5</QUANTITY>
      <UNLIMITED_QUANTITY>false</UNLIMITED_QUANTITY>
    </QUANTITY_WRAPPER>
  </GOODS_CATEGORY>
  <GOODS_CATEGORY>
    <CATEGORY_ID>2</CATEGORY_ID>
    <QUANTITY_WRAPPER>
      <QUANTITY>10</QUANTITY>
      <UNLIMITED_QUANTITY>false</UNLIMITED_QUANTITY>
    </QUANTITY_WRAPPER>
  </GOODS_CATEGORY>
  <GOODS_CATEGORY>
    <CATEGORY_ID>3</CATEGORY_ID>
    <QUANTITY_WRAPPER>
      <QUANTITY />
      <UNLIMITED_QUANTITY>true</UNLIMITED_QUANTITY>
    </QUANTITY_WRAPPER>
  </GOODS_CATEGORY>
</GOODS_CATEGORY_LIST>
"""


sanction_goods = """
<COMMODITY_LIST>
  <COMMODITY>
    <COMMODITY_ID>1</COMMODITY_ID>
    <COMMODITY_DESC>GOODS</COMMODITY_DESC>
    <QUANTITY>5.00</QUANTITY>
    <UNIT>KG</UNIT>
    <VALUE>100.00</VALUE>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>2</COMMODITY_ID>
    <COMMODITY_DESC>MORE</COMMODITY_DESC>
    <QUANTITY>10</QUANTITY>
    <UNIT>KG</UNIT>
    <VALUE>40.23</VALUE>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>3</COMMODITY_ID>
    <COMMODITY_DESC></COMMODITY_DESC>
    <QUANTITY>10</QUANTITY>
    <UNIT>KG</UNIT>
    <VALUE>40.23</VALUE>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID></COMMODITY_ID>
    <COMMODITY_DESC>MORE</COMMODITY_DESC>
    <QUANTITY>10</QUANTITY>
    <UNIT>KG</UNIT>
    <VALUE>40.23</VALUE>
  </COMMODITY>
</COMMODITY_LIST>
""".strip()


cover_letter_text_dfl_v1 = """
<p align="justify" foxid="s1kkAov_plqdkYzdz">Dear Mr Test</p>
<p align="justify" foxid="s1kkAow_plqdkYzdz">
  <b foxid="s1kkAox_plqdkYzdz">Import into the UK from outside the EU or transfer from the EU to the UK of deactivated firearms - Import licence no. <MM foxid="s1kkAoy_plqdkYzdz">LICENCE_NUMBER</MM>
  </b>
</p>
<p><MM>LICENCE_END_DATE</MM>.</p>
"""

cover_letter_text_dfl_v2 = """
<p align="justify">Dear Mr Test</p>
<p align="justify">
  <b>Import into the UK from outside the EU or transfer from the EU to the UK of deactivated firearms - Import licence no. [[LICENCE_NUMBER]]
  </b>
</p>
<p>[[LICENCE_END_DATE]].</p>
"""
