opt_commodities = """
<COMMODITY_LIST>
  <COMMODITY>
    <COMMODITY_ID>1</COMMODITY_ID>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>2</COMMODITY_ID>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>3</COMMODITY_ID>
  </COMMODITY>
</COMMODITY_LIST>
"""

sanctions_emails = """
<SANCTION_EMAIL_LIST>
  <EMAIL_TARGET>IMA_SANCTIONS_EMAIL</EMAIL_TARGET>
  <SUBJECT>Import Sanctions and Adhoc Licence</SUBJECT>
  <TEMPLATE>Email Template</TEMPLATE>
</SANCTION_EMAIL_LIST>
"""

sanctions_commodities = """
<COMMODITY_LIST>
  <COMMODITY>
    <COMMODITY_ID>1</COMMODITY_ID>
    <COMMODITY_DESC>Nice things</COMMODITY_DESC>
    <QUANTITY>3</QUANTITY>
    <UNIT>UNITS</UNIT>
    <VALUE>75</VALUE>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>2</COMMODITY_ID>
    <COMMODITY_DESC>More nice things</COMMODITY_DESC>
    <QUANTITY>1</QUANTITY>
    <UNIT>UNITS</UNIT>
    <VALUE>100</VALUE>
  </COMMODITY>
</COMMODITY_LIST>
"""
