open_variation = """
<VARIATION_REQUEST_LIST>
  <VARIATION_REQUEST>
    <EXTENSION_FLAG>false</EXTENSION_FLAG>
    <STATUS>REJECTED</STATUS>
    <REQUEST_DATE>2022-04-09</REQUEST_DATE>
    <REQUEST_BY_WUA_ID>2</REQUEST_BY_WUA_ID>
    <WHAT_VARIED>Licence extended</WHAT_VARIED>
    <WHY_VARIED>Extension</WHY_VARIED>
    <DATE_VARIED />
    <REJECT_REASON>Wrong</REJECT_REASON>
    <CLOSED_DATE>2022-04-09</CLOSED_DATE>
    <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    <UPDATE_REQUEST_LIST />
  </VARIATION_REQUEST>
  <VARIATION_REQUEST>
    <EXTENSION_FLAG>true</EXTENSION_FLAG>
    <STATUS>OPEN</STATUS>
    <REQUEST_DATE>2022-04-10</REQUEST_DATE>
    <REQUEST_BY_WUA_ID>2</REQUEST_BY_WUA_ID>
    <WHAT_VARIED>Licence extended by 4 months</WHAT_VARIED>
    <WHY_VARIED>Extension request</WHY_VARIED>
    <DATE_VARIED>2022-05-10</DATE_VARIED>
    <REJECT_REASON />
    <CLOSED_DATE />
    <CLOSED_BY_NAME />
    <CLOSED_BY_WUA_ID />
    <UPDATE_REQUEST_LIST>
      <UPDATE_REQUEST>
        <STATUS>CLOSED</STATUS>
        <REQUEST_DATETIME />
        <REQUEST_BY_NAME />
        <REQUEST_BY_WUA_ID />
        <RESPONSE_DATETIME />
        <RESPONSE_BY_NAME />
        <RESPONSE_BY_WUA_ID />
        <REQUEST_TEXT>Closed Update</REQUEST_TEXT>
      </UPDATE_REQUEST>
      <UPDATE_REQUEST>
        <STATUS>WITHDRAWN</STATUS>
        <REQUEST_DATETIME />
        <REQUEST_BY_NAME />
        <REQUEST_BY_WUA_ID />
        <RESPONSE_DATETIME />
        <RESPONSE_BY_NAME />
        <RESPONSE_BY_WUA_ID />
        <REQUEST_TEXT>Withdrawn Update</REQUEST_TEXT>
      </UPDATE_REQUEST>
      <UPDATE_REQUEST>
        <STATUS>OPEN</STATUS>
        <REQUEST_DATETIME />
        <REQUEST_BY_NAME />
        <REQUEST_BY_WUA_ID />
        <RESPONSE_DATETIME />
        <RESPONSE_BY_NAME />
        <RESPONSE_BY_WUA_ID />
        <REQUEST_TEXT>Open Update</REQUEST_TEXT>
      </UPDATE_REQUEST>
    </UPDATE_REQUEST_LIST>
  </VARIATION_REQUEST>
</VARIATION_REQUEST_LIST>
""".strip()


export_varation_1 = """
<VARIATION_LIST>
  <VARIATION>
    <VARIATION_ID>2</VARIATION_ID>
    <STATUS>DELETED</STATUS>
    <OPEN>
      <OPENED_DATETIME />
      <OPENED_BY_WUA_ID />
      <BODY />
    </OPEN>
    <CLOSE>
      <CLOSED_DATETIME />
      <CLOSED_BY_WUA_ID />
    </CLOSE>
    <CANCEL>
      <CANCELLED_DATETIME />
      <CANCELLED_BY_WUA_ID />
    </CANCEL>
    <WITHDRAW>
      <WITHDRAWN_DATETIME />
      <WITHDRAWN_BY_WUA_ID />
    </WITHDRAW>
    <DELETE>
      <DELETED_DATETIME>2022-10-14T12:01:05</DELETED_DATETIME>
      <DELETED_BY_WUA_ID>2</DELETED_BY_WUA_ID>
    </DELETE>
  </VARIATION>
  <VARIATION>
    <VARIATION_ID>1</VARIATION_ID>
    <STATUS>CLOSED</STATUS>
    <OPEN>
      <OPENED_DATETIME>2022-10-13T11:01:05</OPENED_DATETIME>
      <OPENED_BY_WUA_ID>2</OPENED_BY_WUA_ID>
      <BODY>Changes 1</BODY>
    </OPEN>
    <CLOSE>
      <CLOSED_DATETIME>2022-10-14T12:01:05</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <CANCEL>
      <CANCELLED_DATETIME />
      <CANCELLED_BY_WUA_ID />
    </CANCEL>
    <WITHDRAW>
      <WITHDRAWN_DATETIME />
      <WITHDRAWN_BY_WUA_ID />
    </WITHDRAW>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
  </VARIATION>
</VARIATION_LIST>
""".strip()


export_varation_2 = """
<VARIATION_LIST>
  <VARIATION>
    <VARIATION_ID>2</VARIATION_ID>
    <STATUS>OPEN</STATUS>
    <OPEN>
      <OPENED_DATETIME>2022-10-15T11:01:05</OPENED_DATETIME>
      <OPENED_BY_WUA_ID>2</OPENED_BY_WUA_ID>
      <BODY>Changes 3</BODY>
    </OPEN>
    <CLOSE>
      <CLOSED_DATETIME>2022-10-16T12:01:05</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <CANCEL>
      <CANCELLED_DATETIME />
      <CANCELLED_BY_WUA_ID />
    </CANCEL>
    <WITHDRAW>
      <WITHDRAWN_DATETIME />
      <WITHDRAWN_BY_WUA_ID />
    </WITHDRAW>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
  </VARIATION>
  <VARIATION>
    <VARIATION_ID>1</VARIATION_ID>
    <STATUS>CLOSED</STATUS>
    <OPEN>
      <OPENED_DATETIME>2022-10-13T11:01:05</OPENED_DATETIME>
      <OPENED_BY_WUA_ID>2</OPENED_BY_WUA_ID>
      <BODY>Changes 2</BODY>
    </OPEN>
    <CLOSE>
      <CLOSED_DATETIME>2022-10-14T12:01:05</CLOSED_DATETIME>
      <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
    </CLOSE>
    <CANCEL>
      <CANCELLED_DATETIME />
      <CANCELLED_BY_WUA_ID />
    </CANCEL>
    <WITHDRAW>
      <WITHDRAWN_DATETIME />
      <WITHDRAWN_BY_WUA_ID />
    </WITHDRAW>
    <DELETE>
      <DELETED_DATETIME />
      <DELETED_BY_WUA_ID />
    </DELETE>
  </VARIATION>
</VARIATION_LIST>
""".strip()
