open_variation = """
<VARIATION_REQUEST_LIST>
  <VARIATION_REQUEST>
    <EXTENSION_FLAG>true</EXTENSION_FLAG>
    <STATUS>REJECTED</STATUS>
    <REQUEST_DATE>2022-04-09</REQUEST_DATE>
    <REQUEST_BY_WUA_ID>2</REQUEST_BY_WUA_ID>
    <WHAT_VARIED>Licence extended</WHAT_VARIED>
    <WHY_VARIED>Extension</WHY_VARIED>
    <DATE_VARIED />
    <REJECT_REASON>Wrong</REJECT_REASON>
    <CLOSED_DATE>2022-04-09</CLOSED_DATE>
    <CLOSED_BY_WUA_ID>2</CLOSED_BY_WUA_ID>
  </VARIATION_REQUEST>
  <VARIATION_REQUEST>
    <EXTENSION_FLAG>true</EXTENSION_FLAG>
    <STATUS>OPEN</STATUS>
    <REQUEST_DATE>2022-04-10</REQUEST_DATE>
    <REQUEST_BY_WUA_ID>2</REQUEST_BY_WUA_ID>
    <WHAT_VARIED>Licence extended by 4 months</WHAT_VARIED>
    <WHY_VARIED>Extension request</WHY_VARIED>
    <DATE_VARIED>2022-05-10</DATE_VARIED>
    <REJECT_REASON />
    <CLOSED_DATE />
    <CLOSED_BY_NAME />
    <CLOSED_BY_WUA_ID />
    <UPDATE_REQUEST_LIST />
  </VARIATION_REQUEST>
</VARIATION_REQUEST_LIST>
""".strip()
