# Generated by Django 3.1.2 on 2020-11-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="furtherinformationrequest", options={"ordering": ["-requested_datetime"]},
        ),
    ]
