# Generated by Django 4.1.7 on 2023-03-13 11:24
from django.contrib.auth.models import Group, Permission
from django.db import migrations

from web.permissions import Perms


def forwards_func(apps, schema_editor):
    for group_name, permission_codenames in get_groups():
        group = Group.objects.create(name=group_name)

        permissions = Permission.objects.filter(codename__in=permission_codenames)
        group.permissions.set(permissions)


def reverse_func(apps, schema_editor):
    Group.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]


def get_groups():
    return {
        "ILB Case Officer": [
            #
            # Page permissions
            Perms.page.view_permission_harness,
            #
            # Sys permissions
            Perms.sys.ilb_admin,
        ],
        "Importer User": [
            #
            # Page permissions
            # Perms.page.
            #
            # Sys permissions
            Perms.sys.importer_access
        ],
    }
