# Generated by Django 4.1.10 on 2023-09-14 14:22
from django.db import migrations

from web.sites import CASEWORKER_SITE_NAME, EXPORTER_SITE_NAME, IMPORTER_SITE_NAME


def add_icms_sites(apps, schema_editor):
    Site = apps.get_model("sites", "Site")

    Site.objects.create(domain="caseworker-unset", name=CASEWORKER_SITE_NAME)
    Site.objects.create(domain="export-a-certificate-unset", name=EXPORTER_SITE_NAME)
    Site.objects.create(domain="import-a-licence-unset", name=IMPORTER_SITE_NAME)


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_icms_sites),
    ]
