# Generated by Django 3.1.2 on 2020-11-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viewflow", "0009_merge"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportapplication",
            name="further_information_requests",
            field=models.ManyToManyField(to="web.FurtherInformationRequest"),
        ),
        migrations.CreateModel(
            name="FurtherInformationRequestProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "fir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.furtherinformationrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("viewflow.process",),
        ),
        migrations.CreateModel(
            name="ApprovalRequestProcess",
            fields=[
                (
                    "subprocess_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.subprocess",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.approvalrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("viewflow.subprocess",),
        ),
    ]
