# Generated by Django 4.1.10 on 2023-09-14 14:22
from django.db import migrations

from web.sites import SiteName


def add_icms_sites(apps, schema_editor):
    Site = apps.get_model("sites", "Site")

    Site.objects.create(domain="caseworker-unset", name=SiteName.CASEWORKER)
    Site.objects.create(domain="export-a-certificate-unset", name=SiteName.EXPORTER)
    Site.objects.create(domain="import-a-licence-unset", name=SiteName.IMPORTER)


def reverse_icms_sites(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_icms_sites, reverse_icms_sites),
    ]
