# Generated by Django 3.1.1 on 2020-10-02 10:05

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.domains.case.fir.mixins
import web.domains.workbasket.base
import web.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("viewflow", "0009_merge"),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImporterAccessRequestProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                ("restart_approval", models.BooleanField(default=False)),
                ("re_link", models.BooleanField(default=False)),
                (
                    "access_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.accessrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=(web.domains.case.fir.mixins.FurtherInformationProcessMixin, "viewflow.process"),
        ),
        migrations.CreateModel(
            name="FurtherInformationRequestProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "fir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.furtherinformationrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("viewflow.process",),
        ),
        migrations.CreateModel(
            name="ExporterAccessRequestProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                ("restart_approval", models.BooleanField(default=False)),
                ("re_link", models.BooleanField(default=False)),
                (
                    "access_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.accessrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=(web.domains.case.fir.mixins.FurtherInformationProcessMixin, "viewflow.process"),
        ),
        migrations.CreateModel(
            name="ApprovalRequestProcess",
            fields=[
                (
                    "subprocess_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.subprocess",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.approvalrequest",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("viewflow.subprocess",),
        ),
    ]
