# Generated by Django 3.1.1 on 2020-10-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_viewflow"),
    ]

    operations = [
        migrations.AlterModelOptions(name="casenote", options={"ordering": ["-create_datetime"]},),
        migrations.AlterModelOptions(name="file", options={"ordering": ["-created_datetime"]},),
        migrations.AlterField(
            model_name="casenote",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
