# Generated by Django 4.2.11 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_data_add_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificateapplicationtemplate",
            old_name="created",
            new_name="created_datetime",
        ),
        migrations.RenameField(
            model_name="certificateapplicationtemplate",
            old_name="last_updated",
            new_name="last_updated_datetime",
        ),
        migrations.AddField(
            model_name="user",
            name="exporter_last_login",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="importer_last_login",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="certificateapplicationtemplate",
            name="sharing",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private (do not share)"),
                    ("VIEW", "Share (view only)"),
                    ("EDIT", "Share (allow edit)"),
                ],
                help_text="Whether or not other contacts of exporters/agents you are a contact of should be able view and create applications using this template, and if they can edit it.",
                max_length=7,
            ),
        ),
    ]
