# Generated by Django 4.2.11 on 2024-04-22 14:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_data_add_sites"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportApplicationDownloadLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("check_code", models.CharField(editable=False, max_length=8)),
                ("email", models.EmailField(max_length=254)),
                ("failure_count", models.IntegerField(default=0)),
                ("expired", models.BooleanField(default=False)),
                ("sent_at_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "constabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.constabulary",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.importapplicationlicence",
                    ),
                ),
            ],
        ),
    ]
