# Generated by Django 2.2.13 on 2020-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_auto_20200610_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequestprocess",
            name="re_link",
            field=models.BooleanField(default=False),
        ),
    ]
