# Generated by Django 3.1.3 on 2020-11-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_approvalrequest_exporterapprovalrequest_importerapprovalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commoditygroup",
            name="start_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
