# Generated by Django 3.1.2 on 2020-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_case_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("importer_access", "Can act as an importer"),
                    ("exporter_access", "Can act as an exporter"),
                ),
                "managed": False,
                "default_permissions": [],
            },
        ),
        migrations.AlterModelOptions(
            name="exporter",
            options={
                "ordering": ("-is_active", "name"),
                "permissions": [
                    ("is_contact_of_exporter", "Is contact of this exporter"),
                    ("is_agent_of_exporter", "Is agent of this exporter"),
                ],
            },
        ),
    ]
