# Generated by Django 4.2.11 on 2024-04-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_emailtemplate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="manufacturer_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="responsible_person_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="manufacturer_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="responsible_person_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="cfsschedule",
            name="manufacturer_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="cfsscheduletemplate",
            name="manufacturer_address_entry_type",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SEARCH", "Search")],
                default="SEARCH",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
    ]
