# Generated by Django 3.1.2 on 2020-10-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_add_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissions",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": (
                    ("importer_access", "Can act as an importer"),
                    ("exporter_access", "Can act as an exporter"),
                    ("reference_data_access", "Can maintain reference data"),
                    ("mailshot_access", "Can maintain mailshots"),
                ),
            },
        ),
    ]
