# Generated by Django 2.1.8 on 2019-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190508_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_code', models.CharField(blank=True, max_length=50, null=True)),
                ('template_type', models.CharField(choices=[('ENDORSEMENT', 'Endorsement'), ('LETTER_TEMPLATE', 'Letter template'), ('EMAIL_TEMPLATE', 'Email template'), ('CFS_TRANSLATION', 'CFS translation'), ('DECLARATION', 'Declaration')], max_length=20)),
                ('application_domain', models.CharField(choices=[('CA', 'Certificate application'), ('IMA', 'Import application'), ('IAR', 'Access Request')], max_length=20)),
            ],
        ),
    ]
