# Generated by Django 3.1.2 on 2020-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_auto_20201008_1447"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importer",
            options={
                "ordering": ("-is_active", "name"),
                "permissions": [
                    ("is_contact_of_importer", "Is contact of this importer"),
                    ("is_agent_of_importer", "Is agent of this importer"),
                ],
            },
        ),
    ]
