# Generated by Django 4.2.11 on 2024-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_gmp_cfs_address_entry_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfsschedule",
            name="schedule_statements_accordance_with_standards",
            field=models.BooleanField(default=False, verbose_name="Schedule Statements"),
        ),
        migrations.AlterField(
            model_name="cfsschedule",
            name="schedule_statements_is_responsible_person",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="cfsscheduletemplate",
            name="schedule_statements_accordance_with_standards",
            field=models.BooleanField(default=False, verbose_name="Schedule Statements"),
        ),
        migrations.AlterField(
            model_name="cfsscheduletemplate",
            name="schedule_statements_is_responsible_person",
            field=models.BooleanField(default=False, verbose_name=""),
        ),
    ]
