# Generated by Django 4.2.11 on 2024-05-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_cfsschedule_schedule_statements_accordance_with_standards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="silgoodssection5",
            name="subsection",
        ),
        migrations.AddField(
            model_name="silgoodssection5",
            name="section_5_clause",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="web.section5clause",
                verbose_name="Section 5 subsection",
            ),
            preserve_default=False,
        ),
    ]
