# Generated by Django 3.1.2 on 2020-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20201009_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporter", name="comments", field=models.TextField(blank=True, null=True),
        ),
    ]
