# Generated by Django 3.1.4 on 2020-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_section5clause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section5authority",
            name="reference",
            field=models.CharField(
                help_text="Section 5 Authority reference. Example format: '14/A/D/0001'.",
                max_length=50,
                null=True,
            ),
        ),
    ]
