# Generated by Django 3.1.2 on 2020-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_exporter_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporter",
            name="name",
            field=models.CharField(max_length=4000, verbose_name="Organisation Name"),
        ),
        migrations.AlterField(
            model_name="exporter",
            name="registered_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Registered Number"
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="name",
            field=models.CharField(
                blank=True, max_length=4000, null=True, verbose_name="Organisation Name"
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="registered_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Registered Number"
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual"), ("ORGANISATION", "Organisation")],
                max_length=20,
                verbose_name="Entity Type",
            ),
        ),
    ]
