# Generated by Django 4.2.11 on 2024-05-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_remove_silgoodssection5_subsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrygroup",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_active": True},
                related_name="country_groups",
                to="web.country",
            ),
        ),
        migrations.AlterField(
            model_name="countrytranslation",
            name="country",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="web.country",
            ),
        ),
        migrations.AlterField(
            model_name="dflgoodscertificate",
            name="issuing_country",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.country",
                verbose_name="Issuing Country",
            ),
        ),
        migrations.AlterField(
            model_name="importapplication",
            name="consignment_country",
            field=models.ForeignKey(
                help_text="Select the country where the goods were shipped from.",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_applications_to",
                to="web.country",
                verbose_name="Country Of Consignment",
            ),
        ),
        migrations.AlterField(
            model_name="importapplication",
            name="origin_country",
            field=models.ForeignKey(
                help_text="Select the country where the goods were made.",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_applications_from",
                to="web.country",
                verbose_name="Country Of Origin",
            ),
        ),
        migrations.AlterField(
            model_name="importcontact",
            name="country",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.country",
            ),
        ),
        migrations.AlterField(
            model_name="outwardprocessingtradeapplication",
            name="cp_origin_country",
            field=models.ForeignKey(
                help_text="Select the country that the compensating products originate from.",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.country",
                verbose_name="Country Of Origin",
            ),
        ),
        migrations.AlterField(
            model_name="outwardprocessingtradeapplication",
            name="cp_processing_country",
            field=models.ForeignKey(
                help_text="Select the country that the compensating products were processed in.",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.country",
                verbose_name="Country Of Processing",
            ),
        ),
        migrations.AlterField(
            model_name="outwardprocessingtradeapplication",
            name="teg_origin_country",
            field=models.ForeignKey(
                help_text="Select the country, or group of countries (e.g. Any EU Country) that the temporary exported goods originate from.",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.country",
                verbose_name="Country Of Origin",
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="country",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="web.country",
            ),
        ),
    ]
