# Generated by Django 3.1.4 on 2020-12-22 15:10

import django.db.models.deletion
from django.db import migrations, models

import web.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_add_clause_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirearmsAct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("act", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="web.user"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.user",
                    ),
                ),
            ],
            options={
                "ordering": ("act",),
            },
            bases=(web.models.mixins.Archivable, models.Model),
        ),
        migrations.CreateModel(
            name="ActQuantity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("infinity", models.BooleanField(default=False)),
                (
                    "firearmsact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.firearmsact"
                    ),
                ),
                (
                    "firearmsauthority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.firearmsauthority"
                    ),
                ),
            ],
        ),
    ]
