# Generated by Django 2.1.8 on 2019-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190514_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='share_contact_details',
            field=models.BooleanField(default=False),
        ),
    ]
