# Generated by Django 4.2.13 on 2024-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_globalpermission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporter",
            name="exclusive_correspondence",
            field=models.BooleanField(default=False),
        ),
    ]
