# Generated by Django 2.2.13 on 2020-08-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_auto_20200730_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="importer",
            name="eori_number_ni",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NI EORI Number"
            ),
        ),
        migrations.AlterField(
            model_name="importer", name="comments", field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importer",
            name="eori_number",
            field=models.CharField(
                blank=True,
                help_text="EORI number should include the GB prefix",
                max_length=20,
                null=True,
                verbose_name="EORI Number",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="own_importers",
                to="web.User",
                verbose_name="Person",
            ),
        ),
    ]
