# Generated by Django 2.1.8 on 2019-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190514_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboundemail',
            options={'ordering': ('-last_requested_date',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='outboundemail',
            name='last_requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_at_address',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
