# Generated by Django 2.1.8 on 2019-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190516_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.ManyToManyField(to='web.PhoneNumber'),
        ),
    ]
