# Generated by Django 2.1.8 on 2019-05-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_user_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_emails',
            field=models.ManyToManyField(related_name='alternative_users', to='web.EmailAddress'),
        ),
        migrations.CreateModel(
            name='AlternativeEmail',
            fields=[
                ('personalemail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.PersonalEmail')),
            ],
            bases=('web.personalemail',),
        ),
        migrations.AddField(
            model_name='personalemail',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.EmailAddress'),
        ),
        migrations.AddField(
            model_name='personalemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_emails',
            field=models.ManyToManyField(related_name='users', through='web.PersonalEmail', to='web.EmailAddress'),
        ),
    ]
