# Generated by Django 2.2.1 on 2019-05-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(default='WORK', max_length=30)),
                ('portal_notifications', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=4000, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_emails', to='web.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlternativeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(default='WORK', max_length=30)),
                ('portal_notifications', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=4000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_emails', to='web.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
