# Generated by Django 3.1.1 on 2020-09-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_auto_20200828_1043"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateOfManufactureApplication",
            fields=[
                (
                    "exportapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.exportapplication",
                    ),
                ),
                ("is_pesticide_on_free_sale_uk", models.BooleanField(null=True)),
                ("is_manufacturer", models.BooleanField(null=True)),
                ("product_name", models.CharField(max_length=1000)),
                ("chemical_name", models.CharField(max_length=500)),
                ("manufacturing_process", models.TextField(max_length=4000)),
            ],
            bases=("web.exportapplication",),
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("process_type", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="exportapplicationtype", options={"ordering": ("type",)},
        ),
        migrations.RemoveField(model_name="exportapplication", name="id",),
        migrations.RemoveField(model_name="exportapplication", name="is_active",),
        migrations.AlterField(
            model_name="exportapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("STOPPED", "Stopped"),
                    ("REVOKED", "Revoked"),
                    ("VARIATION", "Case Variation"),
                    ("DELETED", "Deleted"),
                ],
                default="IN_PROGRESS",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_type", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="web.user",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next",
                        to="web.task",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="web.process",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exportapplication",
            name="process_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="web.process",
            ),
            preserve_default=False,
        ),
    ]
