# # Generated by Django 3.1.8 on 2021-04-27 11:54
#
from django.db import migrations

constabulary_data = [
    ("Avon & Somerset", "SW", True),
    ("Bedfordshire", "ER", True),
    ("Cambridgeshire", "ER", True),
    ("Central Scotland", "SC", False),
    ("Cumbria", "NW", True),
    ("Cheshire", "NW", True),
    ("City of London", "LO", True),
    ("Cleveland", "NE", True),
    ("Devon & Cornwall", "SW", True),
    ("Dorset", "SW", True),
    ("Dumfries & Galloway", "SC", False),
    ("Durham", "NE", True),
    ("Essex", "ER", True),
    ("Gloucestershire", "SW", True),
    ("Derbyshire", "EM", True),
    ("Dyfed-Powys", "SW", True),
    ("Fife", "SC", False),
    ("Grampian", "SC", False),
    ("Greater Manchester", "NW", True),
    ("Gwent", "SW", True),
    ("Hampshire", "SE", True),
    ("Hertfordshire", "ER", True),
    ("Humberside", "NE", True),
    ("Isle of Man 1", "IM", False),
    ("Kent", "SE", True),
    ("Lancashire", "NW", True),
    ("Leicestershire", "EM", True),
    ("Lincolnshire", "EM", True),
    ("Lothian & Borders", "SC", False),
    ("Merseyside", "NW", True),
    ("Metropolitan", "LO", True),
    ("Norfolk", "ER", True),
    ("North Wales", "NW", True),
    ("North Yorkshire", "NE", True),
    ("Northamptonshire", "EM", True),
    ("Northern", "SC", False),
    ("Northumbria", "NE", True),
    ("Nottingham", "EM", True),
    ("Police Service of Northern Ireland", "RU", True),
    ("South Wales", "SW", True),
    ("South Yorkshire", "NE", True),
    ("Staffordshire", "WM", True),
    ("Strathclyde", "SC", False),
    ("Suffolk", "ER", True),
    ("Surrey", "SE", True),
    ("Sussex", "SE", True),
    ("Tayside", "SC", False),
    ("Thames Valley", "SE", True),
    ("Warwickshire", "WM", True),
    ("West Mercia", "WM", True),
    ("West Midlands", "WM", True),
    ("West Yorkshire", "NE", True),
    ("Wiltshire", "SW", True),
    ("Scotland (Aberdeen)", "SC", True),
    ("Scotland (Dumfries)", "SC", True),
    ("Scotland (Dundee)", "SC", True),
    ("Scotland (Edinburgh)", "SC", True),
    ("Scotland (Glasgow)", "SC", True),
    ("Scotland (Glenrothes)", "SC", True),
    ("Scotland (Inverness)", "SC", True),
    ("Scotland (Stirling)", "SC", True),
    ("Scotland (Scottish Executive)", "SC", True),
    ("Metropolitan Police (ILB use only) closed 30/06/16", "LO", False),
    ("Home Office 1", "LO", True),
    ("Essex (ILB use only 1)", "SE", True),
    ("Essex (ILB use only 2)", "SE", True),
    ("Greater Manchester Police (ILB ONLY)", "NW", True),
    ("West Mercia (ILB Use Only)", "WM", True),
    ("Metropolitan Police (ILB use only)", "LO", True),
    ("MoD - P Sonnex", "LO", False),
    ("Proof House - Birmingham (ILB USE ONLY)", "WM", True),
    ("MoD - D Walker", "LO", True),
    ("Home Office 2", "LO", True),
    ("Home Office 3", "LO", True),
    ("Home Office 4 - section 58(2)", "LO", False),
    ("Home Office 5 - section 58(2)", "LO", True),
    ("Isle of Man 2", "IM", False),
    ("Isle of Man 3", "IM", False),
    ("Isle of Man", "IM", True),
]


def add_constabulary_data(apps, schema_editor):
    Constabulary = apps.get_model("web", "Constabulary")

    new_records = []

    for i, (name, region, is_active) in enumerate(constabulary_data):
        new_records.append(
            Constabulary(
                name=name,
                region=region,
                email=f"constabulary-{i}-{region}@example.com",
                is_active=is_active,
            )
        )

    Constabulary.objects.bulk_create(new_records)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_add_commodity_data"),
    ]

    operations = [
        migrations.RunPython(add_constabulary_data),
    ]
