# Generated by Django 3.1.1 on 2020-09-18 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_auto_20200911_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportapplication",
            name="case_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
