# Generated by Django 3.1.4 on 2021-01-13 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_add_oil_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commoditytype",
            name="type_code",
        ),
        migrations.AddField(
            model_name="commoditytype",
            name="allowed_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10), blank=True, null=True, size=None
            ),
        ),
    ]
