# Generated by Django 3.2.5 on 2021-07-26 13:26

from django.db import migrations

PRODUCT_LEGISLATION_FIELDS = [
    "name",
    "is_active",
    "is_biocidal",
    "is_eu_cosmetics_regulation",
    "is_biocidal_claim",
]

PRODUCT_LEGISLATION_DATA = [
    (
        "EN 301 489-6 V1.3.1 - Electromagnetic compatibility and Radio spectrum Matters (ERM); Electromagnetic Compatibility (EMC) standard for radio equipment and services; Part 6: Specific conditions for Digital Enhanced Cordless Telecommunications (DECT) equipment",
        True,
        False,
        False,
        False,
    ),
    ("Aerosol Dispensers Directive 75/324/EEC", True, False, False, False),
    ("Biocide Products Regulation 528/2012 (EU BPR)", True, True, False, False),
    (
        "Commission Regulation (EU) No 10/2011 on plastic materials and articles intended to come into contact with food",
        True,
        False,
        False,
        False,
    ),
    (
        "Commission Regulation (EU) No 284/2011 laying down specific conditions and detailed procedures for the import of polyamide and melamine plastic kitchenware originating in or consigned from the People’s Republic of China and Hong Kong Special Administrative Region, China",
        False,
        False,
        False,
        False,
    ),
    (
        "EN 301 489-1 V1.9.2 - Electromagnetic compatibility and Radio spectrum Matters (ERM); Electromagnetic Compatibility (EMC) standard for radio equipment and services; Part 1: Common technical requirements",
        True,
        False,
        False,
        False,
    ),
    ("EU Cosmetics Regulation 1223/2009", True, False, True, False),
    ("EU Electromagnetic Compatibility (EMC) Directive 2004/108/EC", False, False, False, False),
    ("General Product Safety Directive 2001/95/EC", True, False, False, False),
    ("IVD Directive 98/79/EC", True, False, False, False),
    ("Low Voltage Directive 2006/95/EEC", False, False, False, False),
    ("Pressure Equipment Directive 97/23/EC", True, False, False, False),
    ("Regulation (EC) 648/2004 on Detergents", True, False, False, False),
    (
        "Regulation (EC) No 1272/2008 on classification, labelling and packaging of substances and mixtures (CLP)",
        True,
        False,
        False,
        False,
    ),
    (
        "Regulation (EC) No 1907/2006 concerning the Registration, Evaluation, Authorisation and Restriction of Chemicals (REACH)",
        True,
        False,
        False,
        False,
    ),
    (
        "Regulation (EC) No 1935/2004 on materials and articles intended to come into contact with food",
        True,
        False,
        False,
        False,
    ),
    (
        "Commission Directive 2011/8/EU amending Directive 2002/72/EC as regards the restriction of use of Bisphenol A in plastic infant feeding bottles",
        True,
        False,
        False,
        False,
    ),
    (
        "Council Directive 84/500/EEC on the approximation of the laws of the Member States relating to ceramic articles intended to come into contact with foodstuffs",
        True,
        False,
        False,
        False,
    ),
    (
        "Chemicals (Hazard Information and Packaging for Supply) Regulations 2009",
        False,
        False,
        False,
        False,
    ),
    ("Toy Safety Directive 2009/48/EC", True, False, False, False),
    ("Council Directive 93/42/EEC concerning medical devices", True, False, False, False),
    (
        "Council Directive 89/686/EEC on the approximation of the laws of the Member States relating to personal protective equipment",
        True,
        False,
        False,
        False,
    ),
    ("Directive 89/686/EEC on personal protective equipment", False, False, False, False),
    (
        "Directive 2011/65/EU on the restriction of the use of certain hazardous substances in electrical and electronic equipment",
        True,
        False,
        False,
        False,
    ),
    ("Machinery Directive 2006/42/EC", True, False, False, False),
    ("EU Fertiliser regulation 2003/2003", True, False, False, False),
    (
        "Council Directive 89/686/EEC relating to personal protective equipment (PPE)",
        False,
        False,
        False,
        False,
    ),
    (
        "Council Regulation (EC) No 834/2007 on organic production and labelling of organic products",
        False,
        False,
        False,
        False,
    ),
    ("Regulation (EC) No 1333/2008 on Food Additives", True, False, False, False),
    ("EU Electromagnetic Compatibility (EMC) Directive 2014/30/EU", True, False, False, False),
    ("Low Voltage Directive 2014/35/EU", True, False, False, False),
    (
        "EN 1504-2 Products and systems for the protection and repair of concrete structures",
        True,
        False,
        False,
        False,
    ),
    (
        "EN 13813 Screed material and floor screeds - Screed materials - Properties and requirements",
        True,
        False,
        False,
        False,
    ),
    (
        "Council Directive relating to personal protective equipment - 89/686/EEC",
        False,
        False,
        False,
        False,
    ),
    (
        "Regulation (EC) No 1830/2003 concerning the traceability and labelling of genetically modified organisms and the traceability of food and feed products produced from genetically modified organisms",
        True,
        False,
        False,
        False,
    ),
]


def add_import_data(apps, schema_editor):
    ProductLegislation = apps.get_model("web", "ProductLegislation")
    ProductLegislation.objects.bulk_create(
        [
            ProductLegislation(**dict(zip(PRODUCT_LEGISLATION_FIELDS, pl_data)))
            for pl_data in PRODUCT_LEGISLATION_DATA
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_add_commodity_group_usage_data"),
    ]

    operations = [
        migrations.RunPython(add_import_data),
    ]
