# Generated by Django 3.1.4 on 2021-01-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_alter_commodity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="importapplication",
            name="commodity_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="web.commoditygroup"
            ),
        ),
    ]
