# Generated by Django 4.2.13 on 2024-06-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_remove_exportapplicationtype_country_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrytranslation",
            name="translation",
            field=models.CharField(max_length=255),
        ),
    ]
