# Generated by Django 2.2.1 on 2019-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190527_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='template_title',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
