# Generated by Django 3.2.5 on 2021-10-15 10:33

from django.db import migrations

sanction_email_data = [
    ("Sanction first contact", True),
    ("Sanction second contact", True),
    ("Sanction third contact", True),
    ("Sanction deactivated contact", False),
]


def add_sanction_email_data(apps, schema_editor):
    SanctionEmail = apps.get_model("web", "SanctionEmail")

    new_records = []

    for i, (name, is_active) in enumerate(sanction_email_data):
        new_records.append(
            SanctionEmail(
                name=name,
                email=f"sanction-{i}@example.com",
                is_active=is_active,
            )
        )

    SanctionEmail.objects.bulk_create(new_records)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_add_product_legislation_data"),
    ]

    operations = [
        migrations.RunPython(add_sanction_email_data),
    ]
