# Generated by Django 3.1.4 on 2021-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_importapplication_commodity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="openindividuallicenceapplication",
            name="know_bought_from",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="openindividuallicenceapplication",
            name="section1",
            field=models.BooleanField(default=True, verbose_name="Section 1"),
        ),
        migrations.AddField(
            model_name="openindividuallicenceapplication",
            name="section2",
            field=models.BooleanField(default=True, verbose_name="Section 2"),
        ),
        migrations.AddField(
            model_name="openindividuallicenceapplication",
            name="commodity_code",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
