# Generated by Django 4.2.13 on 2024-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_caseemail_template_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updaterequest",
            name="response_detail",
            field=models.TextField(
                help_text="Please either confirm acceptance of the updates requested or your reason for no updates being made",
                null=True,
                verbose_name="Response to Request",
            ),
        ),
    ]
