# Generated by Django 3.1.4 on 2021-01-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_userimportcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[("legal", "Legal Person"), ("natural", "Natural Person")],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=200, null=True)),
                ("street", models.CharField(max_length=200, verbose_name="Street and Number")),
                ("city", models.CharField(max_length=200, verbose_name="Town/City")),
                ("postcode", models.CharField(blank=True, max_length=200, null=True)),
                ("region", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dealer",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=10, null=True
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.country",
                    ),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.importapplication"
                    ),
                ),
            ],
        ),
    ]
