# Generated by Django 4.2.13 on 2024-07-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_alter_updaterequest_response_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derogationsapplication",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
        migrations.AlterField(
            model_name="ironsteelapplication",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
        migrations.AlterField(
            model_name="outwardprocessingtradeapplication",
            name="cp_commodities",
            field=models.ManyToManyField(
                related_name="+", to="web.commodity", verbose_name="Commodity Code"
            ),
        ),
        migrations.AlterField(
            model_name="outwardprocessingtradeapplication",
            name="teg_commodities",
            field=models.ManyToManyField(
                related_name="+", to="web.commodity", verbose_name="Commodity Code"
            ),
        ),
        migrations.AlterField(
            model_name="priorsurveillanceapplication",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The value is the total value of all goods under the specified commodity code. It is not the value of a single unit.",
                max_digits=12,
                verbose_name="Value (GBP CIF)",
            ),
        ),
        migrations.AlterField(
            model_name="textilesapplication",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
        migrations.AlterField(
            model_name="woodquotaapplication",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="web.commodity",
                verbose_name="Commodity Code",
            ),
        ),
    ]
