# Generated by Django 2.2.1 on 2019-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190604_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('EM', 'East Midlands'), ('ER', 'Eastern'), ('IM', 'Isle of Man'), ('LO', 'London'), ('NE', 'North East'), ('NW', 'North WEST'), ('RU', 'Royal Ulster'), ('SC', 'Scotland'), ('SE', 'South East'), ('SW', 'South West'), ('WM', 'West Midlands')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='alternativeemail',
            name='type',
            field=models.CharField(choices=[('WORK', 'Work'), ('HOME', 'Home')], default='WORK', max_length=30),
        ),
        migrations.AlterField(
            model_name='personalemail',
            name='type',
            field=models.CharField(choices=[('WORK', 'Work'), ('HOME', 'Home')], default='WORK', max_length=30),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('WORK', 'Work'), ('FAX', 'Fax'), ('MOBILE', 'Mobile'), ('HOME', 'Home'), ('MINICOM', 'Minicom')], default='WORK', max_length=30),
        ),
    ]
