# Generated by Django 3.1.5 on 2021-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_importcontact"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cfsscheduleparagraph",
            constraint=models.UniqueConstraint(fields=("template", "name"), name="unique_name"),
        ),
    ]
