# Generated by Django 2.2.2 on 2019-06-05 12:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('web', '0018_constabularies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teams', serialize=False, to='auth.Group'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='roles', serialize=False, to='auth.Group')),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='web.Team')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
