# Generated by Django 2.2.2 on 2019-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190605_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('commodity_code', models.CharField(max_length=10)),
                ('commodity_type', models.CharField(choices=[('TEXTILES', 'Textiles'), ('IRON_STEEL', 'Iron, Steel and Aluminium'), ('FIREARMS_AMMO', 'Firearms and Ammunition'), ('WOOD', 'Wood'), ('VEHICLES', 'Vehicles'), ('WOOD_CHARCOAL', 'Wood Charcoal'), ('PRECIOUS_METAL_STONE', 'Precious Metals and Stones'), ('OIL_PETROCHEMICALS', 'Oil and Petrochemicals')], max_length=20)),
                ('validity_start_date', models.DateField(blank=True, null=True)),
                ('validity_end_date', models.DateField(blank=True, null=True)),
                ('quantity_threshold', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
