# Generated by Django 3.1.5 on 2021-02-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_verifiedcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("rejected", "REJECTED"),
                            ("accepted", "ACCEPTED"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                ("response", models.TextField()),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "export_application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="web.exportapplication",
                    ),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="web.importapplication",
                    ),
                ),
                (
                    "request_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="web.user"
                    ),
                ),
                (
                    "response_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="withdrawapplication",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("import_application__isnull", False),
                    ("export_application__isnull", False),
                    _connector="OR",
                ),
                name="application_one_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawapplication",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("import_application__isnull", True),
                    ("export_application__isnull", True),
                    _connector="OR",
                ),
                name="application_one_not_null",
            ),
        ),
    ]
