# Generated by Django 2.2.2 on 2019-06-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_commodity_groups_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constabulary',
            name='contacts',
        ),
        migrations.AddField(
            model_name='constabulary',
            name='addresses',
            field=models.ManyToManyField(to='web.Address'),
        ),
        migrations.AddField(
            model_name='constabulary',
            name='members',
            field=models.ManyToManyField(to='web.User'),
        ),
        migrations.AddField(
            model_name='constabulary',
            name='roles',
            field=models.ManyToManyField(to='web.Role'),
        ),
    ]
