# Generated by Django 4.2.14 on 2024-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silapplication",
            name="verified_section5",
            field=models.ManyToManyField(
                related_name="sil_application", to="web.section5authority"
            ),
        ),
    ]
