# Generated by Django 2.2.2 on 2019-06-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_commodity_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=30)),
                ('hmrc_code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='commodity',
            name='validity_start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CommodityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('group_type', models.CharField(choices=[('AUTO', 'Auto'), ('CATEGORY', 'Category')], default='AUTO', max_length=20)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_description', models.CharField(blank=True, max_length=4000, null=True)),
                ('commodities', models.ManyToManyField(blank=True, to='web.Commodity')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Unit')),
            ],
        ),
    ]
