# Generated by Django 2.2.2 on 2019-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_commodity_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='commodity',
            name='sigl_product_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='validity_start_date',
            field=models.DateField(null=True),
        ),
    ]
