# Generated by Django 3.1.5 on 2021-02-09 15:44

from django.db import migrations


def create_case_reference_template(apps, schema_editor):
    Template = apps.get_model("web", "Template")
    Template.objects.get_or_create(
        template_code="STOP_CASE",
        template_type="EMAIL_TEMPLATE",
        application_domain="IMA",
        defaults={
            "template_name": "Stop Case Email",
            "template_title": "ICMS Case Reference [[CASE_REFERENCE]] Stopped",
            "template_content": "Processing on ICMS Case Reference [[CASE_REFERENCE]] has been stopped. Please contact ILB if you believe this is in error or require further information.",
        },
    )


def delete_case_reference_template(apps, schema_editor):
    Template = apps.get_model("web", "Template")
    Template.objects.filter(
        template_code="STOP_CASE",
        template_type="EMAIL_TEMPLATE",
        application_domain="IMA",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_importapplication_case_owner"),
    ]

    operations = [
        migrations.RunPython(create_case_reference_template, delete_case_reference_template),
    ]
