# Generated by Django 2.2.2 on 2019-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_commodity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='sigl_product_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
