# Generated by Django 2.2.2 on 2019-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190619_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='commission_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='hmrc_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
