# Generated by Django 3.1.5 on 2021-02-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_add_case_reference_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionsAndAdhocApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
            ],
            bases=("web.importapplication",),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[("FA", "Firearms and Ammunition"), ("SA", "Sanctions and Adhoc")],
                max_length=70,
            ),
        ),
    ]
