# Generated by Django 4.2.11 on 2024-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_alter_approvalrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="manufacturer_address",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="responsible_person_address",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="manufacturer_address",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="responsible_person_address",
            field=models.CharField(max_length=300, null=True, verbose_name="Address"),
        ),
    ]
