# Generated by Django 3.1.5 on 2021-02-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_auto_20210212_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("FA", "Firearms and Ammunition"),
                    ("SA", "Sanctions and Adhoc"),
                    ("WD", "Wood (Quota)"),
                ],
                max_length=70,
            ),
        ),
    ]
