# Generated by Django 4.2.11 on 2024-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_exportapplication_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="manufacturer_address",
            field=models.CharField(max_length=4000, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplication",
            name="responsible_person_address",
            field=models.CharField(max_length=4000, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="manufacturer_address",
            field=models.CharField(max_length=4000, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="certificateofgoodmanufacturingpracticeapplicationtemplate",
            name="responsible_person_address",
            field=models.CharField(max_length=4000, null=True, verbose_name="Address"),
        ),
    ]
