# Generated by Django 4.2.11 on 2024-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_exportapplication_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfsschedule",
            name="manufacturer_address",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="cfsscheduletemplate",
            name="manufacturer_address",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Address"),
        ),
    ]
