# Generated by Django 4.2.14 on 2024-07-22 16:05
from django.core.management import call_command
from django.db import migrations


def add_reports(apps, schema_editor):
    call_command("loaddata", "reports", app_label="web")


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_alter_cfsschedule_manufacturer_address_and_more"),
    ]

    operations = [
        migrations.RunPython(add_reports, migrations.RunPython.noop),
    ]
