# Generated by Django 3.1.5 on 2021-02-18 13:37

from django.db import migrations


def fix_country_data(apps, schema_editor):
    Country = apps.get_model("web", "Country")

    c = Country.objects.get(name="Congo (Dem. Republic),")
    c.name = "Congo (Dem. Republic)"
    c.save()

    c = Country.objects.get(name="Korea (North),")
    c.name = "Korea (North)"
    c.save()

    c = Country.objects.get(name="Korea (South),")
    c.name = "Korea (South)"
    c.save()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0026_add_country_data"),
    ]

    operations = [
        migrations.RunPython(fix_country_data),
    ]
