# Generated by Django 3.1.5 on 2021-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_fix_country_data"),
    ]
    operations = [
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("name", "is_active"), name="country_group_unique"
            ),
        ),
        migrations.AlterField(
            model_name="countrygroup",
            name="name",
            field=models.CharField(max_length=4000, unique=True),
        ),
    ]
