# Generated by Django 2.2.2 on 2019-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20190625_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlegislation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='commodity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commoditygroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='constabulary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productlegislation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
