# Generated by Django 2.2.2 on 2019-06-26 11:42

from django.db import migrations, models
import django.db.models.deletion
import web.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20190625_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsoleteCalibreGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
            bases=(web.models.mixins.Archivable, models.Model),
        ),
        migrations.CreateModel(
            name='ObsoleteCalibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('calibre_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibres', to='web.ObsoleteCalibreGroup')),
            ],
            bases=(web.models.mixins.Archivable, models.Model),
        ),
    ]
