# Generated by Django 4.2.14 on 2024-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_cfsproduct_schedule_and_product_name_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description_override",
            field=models.CharField(max_length=4096, null=True, verbose_name="Goods Description"),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount_override",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value_override",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Value (GBP CIF)"
            ),
        ),
    ]
