# Generated by Django 4.2.14 on 2024-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_dflgoodscertificate_goods_description_override"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cfsproductactiveingredienttemplate",
            constraint=models.UniqueConstraint(
                fields=("product", "cas_number"), name="template_product_and_cas_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="cfsproductactiveingredienttemplate",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="template_product_and_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="cfsproducttemplate",
            constraint=models.UniqueConstraint(
                fields=("schedule", "product_name"),
                name="template_schedule_and_product_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cfsproducttypetemplate",
            constraint=models.UniqueConstraint(
                fields=("product", "product_type_number"), name="template_product_and_ptn_unique"
            ),
        ),
    ]
