# Generated by Django 3.1.5 on 2021-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_add_exportapplicationtype_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportapplicationtype",
            name="type_code",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
