# Generated by Django 4.2.14 on 2024-08-22 09:52

from django.db import migrations, models


def set_goods_original(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    set_sanctions_goods_original(apps, db_alias)
    set_dfl_goods_original(apps, db_alias)
    set_sil_goods_original(apps, db_alias)


def set_sanctions_goods_original(apps, db_alias):
    SanctionsAndAdhocApplicationGoods = apps.get_model("web", "SanctionsAndAdhocApplicationGoods")

    SanctionsAndAdhocApplicationGoods.objects.using(db_alias).all().update(
        goods_description_original=models.F("goods_description"),
        quantity_amount_original=models.F("quantity_amount"),
        value_original=models.F("value"),
    )


def set_dfl_goods_original(apps, db_alias):
    DFLGoodsCertificate = apps.get_model("web", "DFLGoodsCertificate")

    DFLGoodsCertificate.objects.using(db_alias).all().update(
        goods_description_original=models.F("goods_description")
    )


def set_sil_goods_original(apps, db_alias):
    SILGoodsSection1 = apps.get_model("web", "SILGoodsSection1")
    SILGoodsSection1.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )

    SILGoodsSection2 = apps.get_model("web", "SILGoodsSection2")
    SILGoodsSection2.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )

    SILGoodsSection5 = apps.get_model("web", "SILGoodsSection5")
    SILGoodsSection5.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )

    SILGoodsSection582Obsolete = apps.get_model("web", "SILGoodsSection582Obsolete")
    SILGoodsSection582Obsolete.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )

    SILGoodsSection582Other = apps.get_model("web", "SILGoodsSection582Other")
    SILGoodsSection582Other.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )

    SILLegacyGoods = apps.get_model("web", "SILLegacyGoods")
    SILLegacyGoods.objects.using(db_alias).all().update(
        description_original=models.F("description"), quantity_original=models.F("quantity")
    )


def dummy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_cfsproductactiveingredienttemplate_template_product_and_cas_unique_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dflgoodscertificate",
            name="goods_description_override",
        ),
        migrations.RemoveField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description_override",
        ),
        migrations.RemoveField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount_override",
        ),
        migrations.RemoveField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value_override",
        ),
        migrations.AddField(
            model_name="dflgoodscertificate",
            name="goods_description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount_original",
            field=models.DecimalField(decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value_original",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection1",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection1",
            name="quantity_original",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection2",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection2",
            name="quantity_original",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection5",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection5",
            name="quantity_original",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection582obsolete",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection582obsolete",
            name="quantity_original",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection582other",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="silgoodssection582other",
            name="quantity_original",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sillegacygoods",
            name="description_original",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="sillegacygoods",
            name="quantity_original",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sillegacygoods",
            name="description",
            field=models.CharField(
                help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                max_length=4096,
            ),
        ),
        migrations.AlterField(
            model_name="sillegacygoods",
            name="quantity",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Enter a whole number", null=True
            ),
        ),
        migrations.RunPython(set_goods_original, dummy_reverse),
    ]
