# Generated by Django 2.2.2 on 2019-07-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_default_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTranslationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='obsoletecalibre',
            options={'ordering': ('order',)},
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Country')),
                ('translation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CountryTranslationSet')),
            ],
        ),
    ]
