# Generated by Django 3.1.5 on 2021-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_add_sanctions_country_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionsandadhocapplication",
            name="exporter_address",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsandadhocapplication",
            name="exporter_name",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
