# Generated by Django 3.1.5 on 2021-02-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_alter_sanctions_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importapplicationtype",
            name="declaration_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declaration_application_types",
                to="web.template",
            ),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("FA", "Firearms and Ammunition"),
                    ("SAN", "Sanctions and Adhoc"),
                    ("WD", "Wood (Quota)"),
                ],
                max_length=70,
            ),
        ),
    ]
