# Generated by Django 4.2.14 on 2024-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_user_show_welcome_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseemail",
            name="template_code",
            field=models.CharField(
                choices=[
                    ("IMA_CONSTAB_EMAIL", "Constabulary Email"),
                    ("IMA_SANCTIONS_EMAIL", "Sanctions Email"),
                    ("CA_HSE_EMAIL", "Health and Safety Email"),
                    ("CA_BEIS_EMAIL", "Business, Energy & Industrial Strategy Email"),
                    ("DEACTIVATE_USER", "Deactivate User Email"),
                    ("REACTIVATE_USER", "Reactivate User Email"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                choices=[
                    ("ACCESS_REQUEST", "Access Request"),
                    ("ACCESS_REQUEST_CLOSED", "Access Request Closed"),
                    ("ACCESS_REQUEST_APPROVAL_COMPLETE", "Access Request Approval Complete"),
                    ("APPLICATION_COMPLETE", "Application Complete"),
                    (
                        "APPLICATION_VARIATION_REQUEST_COMPLETE",
                        "Application Variation Request Complete",
                    ),
                    ("APPLICATION_EXTENSION_COMPLETE", "Application Extension Complete"),
                    ("APPLICATION_STOPPED", "Application Stopped"),
                    ("APPLICATION_REFUSED", "Application Refused"),
                    ("APPLICATION_REASSIGNED", "Application Reassigned"),
                    ("APPLICATION_REOPENED", "Application Reopened"),
                    ("APPLICATION_UPDATE", "Application Update"),
                    ("APPLICATION_UPDATE_RESPONSE", "Application Update Response"),
                    ("APPLICATION_UPDATE_WITHDRAWN", "Application Update Withdrawn"),
                    (
                        "EXPORTER_ACCESS_REQUEST_APPROVAL_OPENED",
                        "Exporter Access Request Approval Opened",
                    ),
                    (
                        "IMPORTER_ACCESS_REQUEST_APPROVAL_OPENED",
                        "Importer Access Request Approval Opened",
                    ),
                    ("FIREARMS_SUPPLEMENTARY_REPORT", "Firearms Supplementary Report"),
                    ("CONSTABULARY_DEACTIVATED_FIREARMS", "Constabulary Deactivated Firearms"),
                    ("WITHDRAWAL_ACCEPTED", "Withdrawal Accepted"),
                    ("WITHDRAWAL_CANCELLED", "Withdrawal Cancelled"),
                    ("WITHDRAWAL_OPENED", "Withdrawal Opened"),
                    ("WITHDRAWAL_REJECTED", "Withdrawal Rejected"),
                    (
                        "APPLICATION_VARIATION_REQUEST_CANCELLED",
                        "Application Variation Request Cancelled",
                    ),
                    (
                        "APPLICATION_VARIATION_REQUEST_UPDATE_REQUIRED",
                        "Application Variation Request Update Required",
                    ),
                    (
                        "APPLICATION_VARIATION_REQUEST_UPDATE_CANCELLED",
                        "Application Variation Request Update Cancelled",
                    ),
                    (
                        "APPLICATION_VARIATION_REQUEST_UPDATE_RECEIVED",
                        "Application Variation Request Update Received",
                    ),
                    (
                        "APPLICATION_VARIATION_REQUEST_REFUSED",
                        "Application Variation Request Refused",
                    ),
                    ("CASE_EMAIL", "Case Email"),
                    ("CASE_EMAIL_WITH_DOCUMENTS", "Case Email With Documents"),
                    (
                        "APPLICATION_FURTHER_INFORMATION_REQUEST",
                        "Application Further Information Request",
                    ),
                    (
                        "APPLICATION_FURTHER_INFORMATION_REQUEST_RESPONDED",
                        "Application Further Information Request Responded",
                    ),
                    (
                        "APPLICATION_FURTHER_INFORMATION_REQUEST_WITHDRAWN",
                        "Application Further Information Request Withdrawn",
                    ),
                    (
                        "ACCESS_REQUEST_FURTHER_INFORMATION_REQUEST",
                        "Application Further Information Request",
                    ),
                    (
                        "ACCESS_REQUEST_FURTHER_INFORMATION_REQUEST_RESPONDED",
                        "Access Request Further Information Request Responded",
                    ),
                    (
                        "ACCESS_REQUEST_FURTHER_INFORMATION_REQUEST_WITHDRAWN",
                        "Access Request Further Information Request Withdrawn",
                    ),
                    ("LICENCE_REVOKED", "Licence Revoked"),
                    ("CERTIFICATE_REVOKED", "Certificate Revoked"),
                    ("AUTHORITY_ARCHIVED", "Authority Archived"),
                    ("AUTHORITY_EXPIRING_SECTION_5", "Authority Expiring Section 5"),
                    ("AUTHORITY_EXPIRING_FIREARMS", "Authority Expiring Firearms"),
                    ("MAILSHOT", "Mailshot"),
                    ("RETRACT_MAILSHOT", "Retract Mailshot"),
                    ("NEW_USER_WELCOME", "New User Welcome"),
                    ("ORG_CONTACT_INVITE", "New Organisation Contact Invite"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
