# Generated by Django 4.2.16 on 2024-09-13 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0035_casedocumentreference_web_casedoc_content_e7f950_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="template",
            name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="template",
            name="template_content",
        ),
        migrations.RemoveField(
            model_name="template",
            name="template_title",
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_datetime", models.DateTimeField(auto_now_add=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=4000, null=True)),
                ("content", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="web.template",
                    ),
                ),
            ],
        ),
    ]
