# Generated by Django 2.2.4 on 2019-08-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20190814_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='title',
        ),
        migrations.AddField(
            model_name='importer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_importers', to='web.User'),
        ),
    ]
