# Generated by Django 4.2.16 on 2024-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_template_versioning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportapplication",
            name="case_emails",
            field=models.ManyToManyField(related_name="export_applications", to="web.caseemail"),
        ),
        migrations.AlterField(
            model_name="importapplication",
            name="case_emails",
            field=models.ManyToManyField(related_name="import_applications", to="web.caseemail"),
        ),
        migrations.AddIndex(
            model_name="caseemail",
            index=models.Index(
                fields=["is_active", "status", "template_code"], name="CE_workbasket_idx"
            ),
        ),
    ]
