# Generated by Django 2.2.4 on 2019-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20190818_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='name',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
