# Generated by Django 4.2.16 on 2024-09-30 06:59

from django.db import migrations

from web.domains.template.constants import TemplateCodes


def populate_constabulary_email_template_code(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    CaseEmail = apps.get_model("web", "CaseEmail")
    constabulary_emails = CaseEmail.objects.using(db_alias).filter(
        template_code="", import_applications__application_type__type="FA"
    )

    constabulary_emails.update(template_code=TemplateCodes.IMA_CONSTAB_EMAIL)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_add_case_email_related_name_and_workbasket_index"),
    ]

    operations = [
        migrations.RunPython(populate_constabulary_email_template_code, migrations.RunPython.noop),
    ]
