# Generated by Django 3.1.5 on 2021-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_add_template_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("STOPPED", "Stopped"),
                    ("REVOKED", "Revoked"),
                    ("VARIATION", "Case Variation"),
                    ("DELETED", "Deleted"),
                    ("UPDATE_REQUESTED", "Update Requested"),
                ],
                default="IN_PROGRESS",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="importapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("STOPPED", "Stopped"),
                    ("REVOKED", "Revoked"),
                    ("VARIATION_REQUESTED", "Variation Requested"),
                    ("DELETED", "Deleted"),
                    ("UPDATE_REQUESTED", "Update Requested"),
                ],
                default="IN_PROGRESS",
                max_length=30,
            ),
        ),
    ]
