# Generated by Django 2.2.4 on 2019-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20190818_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=4000, null=True)),
                ('eori_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_entry_type', models.CharField(default='EMPTY', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='constabulary',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='addresses',
        ),
        migrations.AlterField(
            model_name='exporter',
            name='offices',
            field=models.ManyToManyField(to='web.Office'),
        ),
        migrations.AlterField(
            model_name='importer',
            name='offices',
            field=models.ManyToManyField(to='web.Office'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
