# Generated by Django 4.2.16 on 2024-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_constabulary_email_template_code_data_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importcontact",
            name="city",
            field=models.CharField(max_length=200, verbose_name="Town / City"),
        ),
    ]
