# Generated by Django 4.2.16 on 2024-10-21 09:45

from django.db import migrations, models


def populate_sil_legacy_goods_description_original(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    SILLegacyGoods = apps.get_model("web", "SILLegacyGoods")
    legacy_goods = SILLegacyGoods.objects.using(db_alias).filter(description_original__isnull=True)

    legacy_goods.update(description_original=models.F("description"))


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0039_alter_importcontact_city"),
    ]

    operations = [
        migrations.RunPython(
            populate_sil_legacy_goods_description_original, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="dflgoodscertificate",
            name="goods_description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="goods_description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="quantity_amount_original",
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name="sanctionsandadhocapplicationgoods",
            name="value_original",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="silgoodssection1",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="silgoodssection2",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="silgoodssection5",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="silgoodssection582obsolete",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="silgoodssection582obsolete",
            name="quantity_original",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="silgoodssection582other",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="silgoodssection582other",
            name="quantity_original",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="sillegacygoods",
            name="description_original",
            field=models.CharField(max_length=4096),
        ),
    ]
