# Generated by Django 4.2.16 on 2024-10-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0040_import_goods_original_fields_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="silgoodssection1",
            name="import_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_section1",
                to="web.silapplication",
            ),
        ),
        migrations.AlterField(
            model_name="silgoodssection2",
            name="import_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_section2",
                to="web.silapplication",
            ),
        ),
        migrations.AlterField(
            model_name="silgoodssection5",
            name="import_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_section5",
                to="web.silapplication",
            ),
        ),
        migrations.AlterField(
            model_name="silgoodssection582obsolete",  # /PS-IGNORE
            name="import_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_section582_obsoletes",
                to="web.silapplication",
            ),
        ),
        migrations.AlterField(
            model_name="silgoodssection582other",  # /PS-IGNORE
            name="import_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_section582_others",
                to="web.silapplication",
            ),
        ),
    ]
