# Generated by Django 2.2.4 on 2019-08-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_firearmsauthority_section5authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section5authority',
            name='issuing_constabulary',
        ),
    ]
