# Generated by Django 4.2.16 on 2024-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0041_alter_silgoodssection1_import_application_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ironsteelcertificatefile",
            name="file_ptr",
        ),
        migrations.RemoveField(
            model_name="ironsteelchecklist",
            name="import_application",
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("SAN", "Derogation from Sanctions Import Ban"),
                    ("FA", "Firearms and Ammunition"),
                    ("OPT", "Outward Processing Trade"),
                    ("ADHOC", "Sanctions and Adhoc Licence Application"),
                    ("SPS", "Prior Surveillance"),
                    ("TEX", "Textiles (Quota)"),
                    ("WD", "Wood (Quota)"),
                ],
                max_length=70,
            ),
        ),
        migrations.DeleteModel(
            name="IronSteelApplication",
        ),
        migrations.DeleteModel(
            name="IronSteelCertificateFile",
        ),
        migrations.DeleteModel(
            name="IronSteelChecklist",
        ),
    ]
