# Generated by Django 2.2.4 on 2019-08-22 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_remove_section5authority_issuing_constabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_access_requests', to='web.User'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='closed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_access_requests', to='web.User'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='linked_exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='web.Exporter'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='linked_importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='web.Importer'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='reference',
            field=models.CharField(default='IAR/0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='request_reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=30),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='submitted_by',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_access_requests', to='web.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('MAIN_IMPORTER_ACCESS', 'Request access to act as an Importer'), ('AGENT_IMPORTER_ACCESS', 'Request access to act as an Agent for an Importer'), ('MAIN_EXPORTER_ACCESS', 'Request access to act as an Exporter'), ('AGENT_EXPORTER_ACCESS', 'Request access to act as an Agent for an Exporter')], max_length=30),
        ),
    ]
