# Generated by Django 2.2.4 on 2019-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20190822_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='agent_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='agent_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
