# Generated by Django 4.2.16 on 2024-10-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0042_remove_ironsteel_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="derogationschecklist",
            name="import_application",
        ),
        migrations.DeleteModel(
            name="DerogationsApplication",
        ),
        migrations.DeleteModel(
            name="DerogationsChecklist",
        ),
    ]
