# Generated by Django 3.1.5 on 2021-03-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0043_add_tmp_adhoc_sanction_license_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DerogationsApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                ("contract_sign_date", models.DateField(null=True, verbose_name="Expiry Date")),
                (
                    "contract_completion_date",
                    models.DateField(null=True, verbose_name="Expiry Date"),
                ),
                ("explanation", models.CharField(max_length=4096, null=True)),
            ],
            bases=("web.importapplication",),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("FA", "Firearms and Ammunition"),
                    ("SAN", "Derogation from Sanctions Import Ban"),
                    ("SAN_ADHOC_TEMP", "Sanctions and Adhoc"),
                    ("WD", "Wood (Quota)"),
                ],
                max_length=70,
            ),
        ),
    ]
