# Generated by Django 4.2.16 on 2024-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0043_remove_derogationschecklist_import_application_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="submit_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
