# Generated by Django 2.2.4 on 2019-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20190822_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='response',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REFUSED', 'REFUSED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='response_reason',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
