# Generated by Django 3.1.5 on 2021-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_add_derogations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derogationsapplication",
            name="contract_completion_date",
            field=models.DateField(null=True, verbose_name="Contract Completion Date"),
        ),
        migrations.AlterField(
            model_name="derogationsapplication",
            name="contract_sign_date",
            field=models.DateField(null=True, verbose_name="Contract Sign Date"),
        ),
    ]
