# Generated by Django 4.2.16 on 2024-11-13 17:25
from django.conf import settings
from django.db import migrations
from guardian.management import create_anonymous_user

from web.domains.template.models import Template, TemplateCodes

template_type = Template.EMAIL_TEMPLATE
application_domain = Template.IMPORT_APPLICATION
template_code = TemplateCodes.IMA_SANCTIONS_RFI


def create_sanctions_rfi_template(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Template = apps.get_model("web", "Template")
    TemplateVersion = apps.get_model("web", "TemplateVersion")

    new_template = Template.objects.using(db_alias).create(
        is_active=True,
        template_name="Further Information Request Email (Sanctions)",
        template_type=template_type,
        application_domain=application_domain,
        template_code=template_code,
    )

    # we need to create an anonymous user to create the template, this should have already been done but in the case
    # of initial setup, the post-migration signal to create the user has not been run yet, so we need to manually create it.
    create_anonymous_user(sender=None, using="default")

    TemplateVersion.objects.using(db_alias).create(
        template=new_template,
        created_by_id=0,
        title="Request for more information [[CASE_REFERENCE]]",
        content="Dear [[IMPORTER_NAME]],\n\nYou need to provide some more information for Import Licencing Branch (ILB) to process your application.\n\n[DESCRIBE WHAT INFORMATION OR CLARIFICATION IS NEEDED. INCLUDE SUGGESTIONS IF RELEVANT]\n\nregarding [DESCRIBE WHAT FURTHER INFORMATION IS NEEDED / WHAT IS UNCLEAR, MAKE SUGGESTIONS IF RELEVANT].\n\nYour application will not be processed further until you respond to this request.\n\nThe application will be closed if the requested response is not received within 1 working day of this email.\n\nContact [[SANCTIONS_EMAIL_ADDRESS]] if you have any questions about your application.\n\nInclude case reference number [[CASE_REFERENCE]] in your email, so we know which application you are contacting us about.\n\nYours sincerely,\n\n[[CASE_OFFICER_NAME]]",
    )


def delete_sanctions_rfi_template(apps, schema_editor):
    Template = apps.get_model("web", "Template")
    Template.objects.filter(template_code=TemplateCodes.IMA_SANCTIONS_RFI).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("guardian", "0002_generic_permissions_index"),
        ("web", "0045_alter_globalpermission_options"),
    ]

    operations = [
        migrations.RunPython(
            create_sanctions_rfi_template, reverse_code=delete_sanctions_rfi_template
        )
    ]
