# Generated by Django 2.2.4 on 2019-08-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20190822_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='response',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REFUSED', 'Refused')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('REFUSE', 'OPEN')], max_length=20, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REFUSE', 'Refuse')], max_length=20, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_reason', models.CharField(blank=True, max_length=4000, null=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AccessRequest')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='web.User')),
                ('requested_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approval_requests', to='web.User')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_approval_requests', to='web.User')),
            ],
        ),
    ]
