# Generated by Django 3.1.5 on 2021-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0046_add_derogations_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanctionsandadhocapplication",
            name="supporting_documents",
            field=models.ManyToManyField(to="web.File"),
        ),
    ]
