# Generated by Django 5.1.3 on 2024-12-09 14:28

from django.db import migrations

import web.domains.office.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0047_ecilexample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="address_1",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 1"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_2",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 2"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_3",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 3"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_4",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 4"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_5",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 5"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_6",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 6"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_7",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 7"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="address_8",
            field=web.domains.office.model_fields.AddressLineField(
                blank=True, max_length=100, null=True, verbose_name="Address line 8"
            ),
        ),
    ]
