# Generated by Django 3.1.5 on 2021-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0047_sanctionsandadhocapplication_supporting_documents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="derogationsapplication",
            old_name="quantity_amount",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="derogationsapplication",
            name="unit",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="derogationsapplication",
            name="commodity_code",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
