# Generated by Django 3.1.6 on 2021-04-15 15:43

from django.db import migrations, models

import web.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0048_alter_derogations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, verbose_name="Email Address")),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(web.models.mixins.Archivable, models.Model),
        ),
    ]
