# Generated by Django 2.2.4 on 2019-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_importapplicationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importapplicationtype',
            name='sub_type',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
