# Generated by Django 2.2.4 on 2019-08-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20190827_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importapplicationtype',
            name='declaration_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaration_application_types', to='web.Template'),
        ),
        migrations.AlterField(
            model_name='importapplicationtype',
            name='endorsements',
            field=models.ManyToManyField(related_name='endorsement_application_types', to='web.Template'),
        ),
    ]
