# Generated by Django 5.1.5 on 2025-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_alter_countrygroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="verified_reminder_count",
            field=models.IntegerField(default=0),
        ),
    ]
