# Generated by Django 3.1.8 on 2021-04-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0050_derogationsapplication_supporting_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionEmailMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(default="DRAFT", max_length=30)),
                ("to", models.CharField(blank=True, max_length=4000, null=True)),
                ("cc_address_list", models.CharField(blank=True, max_length=4000, null=True)),
                ("subject", models.CharField(max_length=100, null=True)),
                ("body", models.TextField(max_length=4000, null=True)),
                ("response", models.TextField(blank=True, max_length=4000, null=True)),
                ("sent_datetime", models.DateTimeField(blank=True, null=True)),
                ("closed_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanction_emails",
                        to="web.sanctionsandadhocapplication",
                    ),
                ),
                ("attachments", models.ManyToManyField(to="web.File")),
            ],
        ),
    ]
