# Generated by Django 3.1.8 on 2021-04-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0051_sanctionemailmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constabularyemail",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="constabulary_emails",
                to="web.openindividuallicenceapplication",
            ),
        ),
    ]
