# Generated by Django 5.1.5 on 2025-01-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0052_userfeedbacksurvey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECILMultiStepExample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "favourite_colour",
                    models.CharField(
                        choices=[("blue", "Blue"), ("red", "Red"), ("yellow", "Yellow")],
                        help_text="Pick a colour",
                        max_length=6,
                        verbose_name="What's your favourite primary colour",
                    ),
                ),
                (
                    "likes_cake",
                    models.BooleanField(
                        help_text="Enter a value", verbose_name="Do you like cake?"
                    ),
                ),
                (
                    "favourite_book",
                    models.CharField(
                        help_text="Enter a value", max_length=255, verbose_name="Favourite book"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
