# Generated by Django 5.1.5 on 2025-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0053_ecilmultistepexample"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="organisation_products",
            field=models.TextField(default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="organisation_purpose",
            field=models.TextField(
                default="",
                help_text="Explain what the company does. For example, produces and sells cosmetics.",
                max_length=2000,
                verbose_name="What does the company do?",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="organisation_trading_name",
            field=models.CharField(
                blank=True,
                help_text="You only need to enter a trading name if it's different from the company name",
                max_length=100,
                null=True,
                verbose_name="Trading name",
            ),
        ),
        migrations.AddField(
            model_name="exporteraccessrequest",
            name="export_countries",
            field=models.ManyToManyField(related_name="+", to="web.country"),
        ),
    ]
