# Generated by Django 2.2.4 on 2019-08-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_importapplication_importer_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('note', models.CharField(blank=True, max_length=4000, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ImportCase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_import_case_notes', to='web.User')),
            ],
        ),
    ]
