# Generated by Django 2.2.4 on 2019-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_importcasenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcasenote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
