# Generated by Django 5.1.5 on 2025-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0054_accessrequest_organisation_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporteraccessrequest",
            name="export_countries",
            field=models.ManyToManyField(related_name="+", to="web.country"),
        ),
    ]
