# Generated by Django 5.1.5 on 2025-02-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0054_accessrequest_organisation_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedbacksurvey",
            name="referrer_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userfeedbacksurvey",
            name="additional_support",
            field=models.CharField(
                choices=[
                    ("NO", "No, I didn’t need any additional support "),
                    ("EMAILED", "Yes, I emailed asking for additional support"),
                    ("COULD_NOT_FIND", "Yes, but I could not find any additional support"),
                    ("DONT_KNOW", "I don’t know "),
                ],
                default="",
                max_length=16,
                null=True,
                verbose_name="Did you need any additional support at any point during the application?",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedbacksurvey",
            name="find_service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERY_EASY", "Very Easy"),
                    ("EASY", "Easy"),
                    ("NEITHER", "Neither easy or difficult"),
                    ("DIFFICULT", "Difficult"),
                    ("VERY_DIFFICULT", "Very difficult"),
                ],
                default="",
                max_length=16,
                verbose_name="How was the process of finding the service?",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedbacksurvey",
            name="future_contact",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                default="",
                max_length=3,
                verbose_name="Would you be happy for us to contact you in the future to help us improve the service?",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedbacksurvey",
            name="process",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="web.process"
            ),
        ),
    ]
