# Generated by Django 5.1.5 on 2025-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0055_userfeedbacksurvey_referrer_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="agent_trading_name",
            field=models.CharField(
                blank=True,
                help_text="You only need to enter a trading name if it's different from the company name",
                max_length=100,
                null=True,
                verbose_name="Trading name",
            ),
        ),
    ]
