# Generated by Django 5.1.5 on 2025-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0056_accessrequest_agent_trading_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="agent_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="agent_trading_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="You only need to enter a trading name if it's different from the company name",
                max_length=100,
                verbose_name="Trading name",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="organisation_trading_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="You only need to enter a trading name if it's different from the company name",
                max_length=100,
                verbose_name="Trading name",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="response",
            field=models.CharField(
                choices=[("APPROVED", "Approved"), ("REFUSED", "Refused")],
                default="",
                max_length=20,
            ),
        ),
    ]
