# Generated by Django 2.2.4 on 2019-08-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_importfurtherinformationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=30)),
                ('request_subject', models.CharField(max_length=100, null=True)),
                ('request_detail', models.CharField(max_length=4000, null=True)),
                ('email_cc_address_list', models.CharField(blank=True, max_length=4000, null=True)),
                ('response_detail', models.CharField(max_length=4000, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ImportCase')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_import_application_updates', to='web.User')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_import_application_updates', to='web.User')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_import_application_updates', to='web.User')),
            ],
        ),
    ]
