# Generated by Django 2.2.4 on 2019-09-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_importupdaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('is_email', models.BooleanField()),
                ('email_subject', models.CharField(max_length=78, null=True)),
                ('email_body', models.CharField(max_length=4000, null=True)),
                ('is_retraction_email', models.BooleanField()),
                ('retract_email_subject', models.CharField(max_length=78, null=True)),
                ('retract_email_body', models.CharField(max_length=4000, null=True)),
                ('is_to_importers', models.BooleanField(default=False)),
                ('is_to_exporters', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('published_datetime', models.DateTimeField(null=True)),
                ('retracted_datetime', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mailshots', to='web.User')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_mailshots', to='web.User')),
                ('retracted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retracted_mailshots', to='web.User')),
            ],
        ),
    ]
