# Generated by Django 2.2.4 on 2019-09-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_mailshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importapplicationtype',
            name='consignment_country_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_application_types_to', to='web.CountryGroup'),
        ),
        migrations.AlterField(
            model_name='importapplicationtype',
            name='master_country_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_application_types', to='web.CountryGroup'),
        ),
        migrations.AlterField(
            model_name='importapplicationtype',
            name='origin_country_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_application_types_from', to='web.CountryGroup'),
        ),
        migrations.CreateModel(
            name='ExportApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('type_code', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=70)),
                ('allow_multiple_products', models.BooleanField()),
                ('generate_cover_letter', models.BooleanField()),
                ('allow_hse_authorization', models.BooleanField()),
                ('country_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.CountryGroup')),
                ('country_group_for_manufacture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacture_export_application_types', to='web.CountryGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExportApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('submit_datetime', models.DateTimeField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ExportApplicationType')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_export_applications', to='web.User')),
                ('countries', models.ManyToManyField(to='web.Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_export_applications', to='web.User')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_applications', to='web.Exporter')),
                ('exporter_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_export_applications', to='web.Office')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_export_application', to='web.User')),
            ],
        ),
    ]
