# Generated by Django 5.1.5 on 2025-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0059_alter_globalpermission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportapplication",
            name="applicant_reference",
            field=models.CharField(
                default="",
                help_text="Give the application a reference name so you can refer back to it when needed",
                max_length=100,
                verbose_name="Name the application",
            ),
        ),
    ]
