# Generated by Django 3.1.8 on 2021-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0059_derogationschecklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firearmsauthority",
            name="reference",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="section5authority",
            name="reference",
            field=models.CharField(
                help_text="Section 5 Authority reference. Example format: '14/A/D/0001'.",
                max_length=100,
                null=True,
            ),
        ),
    ]
