# Generated by Django 5.1.5 on 2025-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_exportapplication_applicant_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importeraccessrequest",
            name="eori_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="EORI number should include the GB prefix",
                max_length=20,
                verbose_name="EORI Number",
            ),
        ),
    ]
