# Generated by Django 3.1.8 on 2021-05-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0060_alter_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="DFLApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                (
                    "deactivated_firearm",
                    models.BooleanField(default=True, verbose_name="Deactivated Firearm"),
                ),
                ("proof_checked", models.BooleanField(default=False, verbose_name="Proof Checked")),
                (
                    "commodity_code",
                    models.CharField(
                        choices=[
                            ("ex Chapter 93", "ex Chapter 93"),
                            ("ex Chapter 97", "ex Chapter 97"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Commodity Code",
                    ),
                ),
                (
                    "know_bought_from",
                    models.BooleanField(
                        null=True,
                        verbose_name="Do you know who you plan to buy/obtain these items from?",
                    ),
                ),
                (
                    "constabulary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.constabulary",
                    ),
                ),
            ],
            bases=("web.importapplication",),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Open Individual Import Licence"),
                    ("DEACTIVATED", "Deactivated Firearms Import Licence"),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
