# Generated by Django 2.2.4 on 2019-09-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_exportcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCaseVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('DELETED', 'Deleted'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], max_length=30)),
                ('variation_reason', models.CharField(blank=True, max_length=4000, null=True)),
                ('opened_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('closed_datetime', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ExportCase')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_export_variations', to='web.User')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_export_variations', to='web.User')),
            ],
        ),
    ]
