# Generated by Django 5.1.7 on 2025-03-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_alter_importapplicationtype_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NuclearMaterialApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                ("exporter_name", models.CharField(blank=True, max_length=4096, null=True)),
                ("exporter_address", models.CharField(blank=True, max_length=4096, null=True)),
                ("supporting_documents", models.ManyToManyField(to="web.file")),
            ],
            options={
                "abstract": False,
            },
            bases=("web.importapplication",),
        ),
        migrations.CreateModel(
            name="NuclearMaterialApplicationGoods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "goods_description",
                    models.CharField(max_length=4096, verbose_name="Goods Description"),
                ),
                (
                    "quantity_amount",
                    models.DecimalField(decimal_places=3, max_digits=14, verbose_name="Quantity"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The value is the total value of all goods under the specified commodity code. It is not the value of a single unit.",
                        max_digits=12,
                        verbose_name="Value (GBP CIF)",
                    ),
                ),
                ("goods_description_original", models.CharField(max_length=4096)),
                ("quantity_amount_original", models.DecimalField(decimal_places=3, max_digits=14)),
                ("value_original", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.commodity",
                        verbose_name="Commodity Code",
                    ),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclear_goods",
                        to="web.importapplication",
                    ),
                ),
            ],
        ),
    ]
