# Generated by Django 3.1.8 on 2021-05-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0061_add_dflapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="SILUserSection5",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.file",
                    ),
                ),
            ],
            bases=("web.file",),
        ),
        migrations.CreateModel(
            name="SILApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                ("section1", models.BooleanField(default=False, verbose_name="Section 1")),
                ("section2", models.BooleanField(default=False, verbose_name="Section 2")),
                ("section5", models.BooleanField(default=False, verbose_name="Section 5")),
                (
                    "section58_obsolete",
                    models.BooleanField(
                        default=False, verbose_name="Section 58(2) - Obsolete Calibre"
                    ),
                ),
                (
                    "section58_other",
                    models.BooleanField(default=False, verbose_name="Section 58(2) - Other"),
                ),
                (
                    "other_description",
                    models.CharField(
                        blank=True,
                        help_text="If you have selected Other in Firearms Act Sections. Please explain why you are making this request under this 'Other' section.",
                        max_length=4000,
                        null=True,
                        verbose_name="Other Section Description",
                    ),
                ),
                (
                    "military_police",
                    models.BooleanField(
                        null=True, verbose_name="Are any of your items for the military or police?"
                    ),
                ),
                (
                    "eu_single_market",
                    models.BooleanField(
                        null=True,
                        verbose_name="Were any of your items in the EU Single Market before 14 September 2018?",
                    ),
                ),
                (
                    "manufactured",
                    models.BooleanField(
                        null=True,
                        verbose_name="Were any of your items manufactured before 1 September 1939?",
                    ),
                ),
                (
                    "commodity_code",
                    models.CharField(
                        choices=[
                            ("ex Chapter 93", "ex Chapter 93"),
                            ("ex Chapter 97", "ex Chapter 97"),
                        ],
                        help_text='You must pick the commodity code group that applies to the items that you wish to import. Please note that "ex Chapter 97" is only relevant to collectors pieces and items over 100 years old. Please contact HMRC classification advisory service, 01702 366077, if you are unsure of the correct code.',
                        max_length=40,
                        null=True,
                        verbose_name="Commodity Code",
                    ),
                ),
                ("know_bought_from", models.BooleanField(null=True)),
                ("additional_comments", models.CharField(blank=True, max_length=4000, null=True)),
                (
                    "user_section5",
                    models.ManyToManyField(
                        related_name="sil_application", to="web.SILUserSection5"
                    ),
                ),
                (
                    "verified_section5",
                    models.ManyToManyField(related_name="+", to="web.Section5Authority"),
                ),
                (
                    "user_imported_certificates",
                    models.ManyToManyField(
                        related_name="sil_application", to="UserImportCertificate"
                    ),
                ),
                (
                    "verified_certificates",
                    models.ManyToManyField(related_name="sil_application", to="FirearmsAuthority"),
                ),
            ],
            bases=("web.importapplication",),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIL", "Open Individual Import Licence"),
                    ("DEACTIVATED", "Deactivated Firearms Import Licence"),
                    ("SIL", "Specific Import Licence"),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
