# Generated by Django 3.1.8 on 2021-05-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_add_silapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="DFLGoodsCertificate",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.file",
                    ),
                ),
                (
                    "goods_description",
                    models.CharField(max_length=4096, verbose_name="Goods Description"),
                ),
                (
                    "deactivated_certificate_reference",
                    models.CharField(
                        max_length=50, verbose_name="Deactivated Certificate Reference"
                    ),
                ),
                (
                    "issuing_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.country",
                        verbose_name="Issuing Country",
                    ),
                ),
            ],
            bases=("web.file",),
        ),
        migrations.AddField(
            model_name="dflapplication",
            name="goods_certificates",
            field=models.ManyToManyField(
                related_name="_dflapplication_goods_certificates_+", to="web.DFLGoodsCertificate"
            ),
        ),
    ]
