# Generated by Django 5.1.7 on 2025-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0062_alter_countrygroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("SAN", "Derogation from Sanctions Import Ban"),
                    ("FA", "Firearms and Ammunition"),
                    ("NMIL", "Nuclear Materials Import Licence Application"),
                    ("OPT", "Outward Processing Trade"),
                    ("ADHOC", "Sanctions and Adhoc Licence Application"),
                    ("SPS", "Prior Surveillance"),
                    ("TEX", "Textiles (Quota)"),
                    ("WD", "Wood (Quota)"),
                ],
                max_length=70,
            ),
        ),
    ]
