# Generated by Django 5.1.7 on 2025-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_alter_importapplicationtype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="hmrc_code",
            field=models.CharField(max_length=4),
        ),
    ]
