# Generated by Django 3.1.8 on 2021-05-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0063_add_dflgoodscertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SILGoodsSection582Other",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "curiosity_ornament",
                    models.BooleanField(
                        null=True,
                        verbose_name="Do you intend to possess the firearm as a 'curiosity or ornament'?",
                    ),
                ),
                (
                    "acknowledgment",
                    models.BooleanField(
                        default=False, verbose_name="Do you acknowledge the above statement?"
                    ),
                ),
                (
                    "manufacture",
                    models.BooleanField(
                        null=True,
                        verbose_name="Was the firearm manufactured after 1899 and before 1939?",
                    ),
                ),
                (
                    "muzzle_loading",
                    models.BooleanField(null=True, verbose_name="Is the firearm muzzle-loading?"),
                ),
                (
                    "rimfire",
                    models.BooleanField(
                        null=True,
                        verbose_name="Is the firearm breech-loading capable of discharging a rimfire cartridge other than .22 inch, .23 inch, 6mm or 9mm?",
                    ),
                ),
                (
                    "rimfire_details",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="If Yes, please specify"
                    ),
                ),
                (
                    "ignition",
                    models.BooleanField(
                        null=True,
                        verbose_name="Is the firearm breech-loading using an ignition system other than rimfire or centrefire?",
                    ),
                ),
                (
                    "ignition_details",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pin-fire", "Pin-fire"),
                            ("Needle-fire", "Needle-fire"),
                            ("Lip-fire", "Lip-fire"),
                            ("Cup primed", "Cup primed"),
                            ("Teat-fire", "Teat-fire"),
                            ("Base-fire", "Base-fire"),
                            ("Other", "Other"),
                        ],
                        max_length=12,
                        verbose_name="If Yes, please specify ignition system",
                    ),
                ),
                (
                    "ignition_other",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="If Other, please specify"
                    ),
                ),
                (
                    "chamber",
                    models.BooleanField(
                        help_text="32 bore, 24 bore, 14 bore, 10 bore (2 5/8 and 2 7/8 inch only), 8 bore, 4 bore, 3 bore, 2 bore, 1 1/8 bore, 1 1/2 bore, 1 1/4 bore",
                        null=True,
                        verbose_name="Is the firearm a shotgun, punt gun or rifle chambered for one of the following cartridges (expressed in imperial measurements)?",
                    ),
                ),
                (
                    "bore",
                    models.BooleanField(
                        null=True,
                        verbose_name="Is the firearm a shotgun, punt gun or rifle with a bore greater than 10?",
                    ),
                ),
                (
                    "bore_details",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="If Yes, please specify",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Enter a whole number"),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_section582_others",
                        to="web.silapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SILGoodsSection582Obsolete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "curiosity_ornament",
                    models.BooleanField(
                        null=True,
                        verbose_name="Do you intend to possess the firearm as a 'curiosity or ornament'?",
                    ),
                ),
                (
                    "acknowledgment",
                    models.BooleanField(
                        default=False, verbose_name="Do you acknowledge the above statement?"
                    ),
                ),
                (
                    "centrefire",
                    models.BooleanField(
                        null=True, verbose_name="Is this a breech-loading centrefire firearm?"
                    ),
                ),
                (
                    "manufacture",
                    models.BooleanField(
                        null=True,
                        verbose_name="Was the firearm manufactured after 1899 and before 1939?",
                    ),
                ),
                (
                    "original_chambering",
                    models.BooleanField(
                        null=True, verbose_name="Does the firearm retain its original chambering?"
                    ),
                ),
                (
                    "obsolete_calibre",
                    models.CharField(max_length=50, verbose_name="Obsolete Calibre"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Enter a whole number"),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_section582_obsoletes",
                        to="web.silapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SILGoodsSection5",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subsection",
                    models.CharField(max_length=300, verbose_name="Section 5 subsection"),
                ),
                (
                    "manufacture",
                    models.BooleanField(
                        null=True, verbose_name="Was the firearm manufactured before 1900?"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Enter a whole number", null=True
                    ),
                ),
                (
                    "unlimited_quantity",
                    models.BooleanField(default=False, verbose_name="Unlimited Quantity"),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_section5",
                        to="web.silapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SILGoodsSection2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "manufacture",
                    models.BooleanField(
                        null=True, verbose_name="Was the firearm manufactured before 1900?"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Enter a whole number"),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_section2",
                        to="web.silapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SILGoodsSection1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "manufacture",
                    models.BooleanField(
                        null=True, verbose_name="Was the firearm manufactured before 1900?"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Enter a whole number"),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_section1",
                        to="web.silapplication",
                    ),
                ),
            ],
        ),
    ]
