# Generated by Django 2.2.4 on 2019-09-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_auto_20190905_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=300, null=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('browser_content_type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('file_size', models.IntegerField(null=True)),
                ('path', models.CharField(blank=True, max_length=4000, null=True)),
                ('error_message', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.User')),
            ],
        ),
        migrations.AddField(
            model_name='casenote',
            name='files',
            field=models.ManyToManyField(to='web.File'),
        ),
        migrations.AddField(
            model_name='firearmsauthority',
            name='files',
            field=models.ManyToManyField(to='web.File'),
        ),
        migrations.AddField(
            model_name='furtherinformationrequest',
            name='files',
            field=models.ManyToManyField(to='web.File'),
        ),
        migrations.AddField(
            model_name='mailshot',
            name='files',
            field=models.ManyToManyField(to='web.File'),
        ),
        migrations.AddField(
            model_name='section5authority',
            name='files',
            field=models.ManyToManyField(to='web.File'),
        ),
    ]
