# Generated by Django 5.1.7 on 2025-03-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0064_alter_unit_hmrc_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="NuclearMaterialApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                (
                    "nature_of_business",
                    models.CharField(
                        default="", max_length=4096, verbose_name="Nature of Business"
                    ),
                ),
                (
                    "consignor_name",
                    models.CharField(
                        default="", max_length=4096, verbose_name="Consignor Company Name"
                    ),
                ),
                (
                    "consignor_address",
                    models.CharField(
                        default="",
                        max_length=4096,
                        verbose_name="Consignor Company Address and Postcode",
                    ),
                ),
                (
                    "end_user_name",
                    models.CharField(
                        default="", max_length=4096, verbose_name="End User Company Name"
                    ),
                ),
                (
                    "end_user_address",
                    models.CharField(
                        default="",
                        max_length=4096,
                        verbose_name="End User Company Address and Postcode",
                    ),
                ),
                (
                    "intended_use_of_shipment",
                    models.TextField(default="", verbose_name="Intended use of shipment"),
                ),
                (
                    "dates_of_shipment",
                    models.CharField(
                        default="", max_length=200, verbose_name="Date(s) of shipments"
                    ),
                ),
                (
                    "security_team_contact_information",
                    models.TextField(
                        default="", verbose_name="Contact information for security team"
                    ),
                ),
                (
                    "licence_type",
                    models.CharField(
                        choices=[("S", "Single"), ("O", "Open")],
                        default="",
                        max_length=1,
                        verbose_name="Single or Open Licence",
                    ),
                ),
                ("supporting_documents", models.ManyToManyField(to="web.file")),
            ],
            options={
                "abstract": False,
            },
            bases=("web.importapplication",),
        ),
        migrations.CreateModel(
            name="NuclearMaterialApplicationGoods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "goods_description",
                    models.CharField(
                        max_length=4096, verbose_name="Goods Description (Including UN Number)"
                    ),
                ),
                (
                    "quantity_amount",
                    models.DecimalField(decimal_places=3, max_digits=14, verbose_name="Quantity"),
                ),
                ("goods_description_original", models.CharField(max_length=4096)),
                ("quantity_amount_original", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.commodity",
                        verbose_name="Commodity Code",
                    ),
                ),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuclear_goods",
                        to="web.importapplication",
                    ),
                ),
                (
                    "quantity_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="web.unit"
                    ),
                ),
            ],
        ),
    ]
