# Generated by Django 3.1.8 on 2021-05-25 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0064_silgoodssections"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutwardProcessingTradeApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                (
                    "customs_office_name",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Requested customs supervising office name",
                    ),
                ),
                (
                    "customs_office_address",
                    models.TextField(
                        max_length=4000,
                        null=True,
                        verbose_name="Requested customs supervising office address",
                    ),
                ),
                (
                    "rate_of_yield",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Rate of yield (kg per garment)",
                    ),
                ),
                (
                    "rate_of_yield_calc_method",
                    models.TextField(
                        blank=True,
                        max_length=4000,
                        null=True,
                        verbose_name="Rate of yield calculation method",
                    ),
                ),
                (
                    "last_export_day",
                    models.DateField(
                        help_text="Requested last day of authorised exportation.", null=True
                    ),
                ),
                (
                    "reimport_period",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Period for re-importation (months)",
                    ),
                ),
                (
                    "nature_process_ops",
                    models.TextField(
                        max_length=4000, null=True, verbose_name="Nature of processing operations"
                    ),
                ),
                (
                    "suggested_id",
                    models.TextField(
                        help_text="Enter the suggested means of identification of re-imported compensating products.",
                        max_length=4000,
                        null=True,
                        verbose_name="Suggested means of identification",
                    ),
                ),
                (
                    "cp_category",
                    models.CharField(
                        choices=[
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("15", "15"),
                            ("21", "21"),
                            ("24", "24"),
                            ("26", "26"),
                            ("27", "27"),
                            ("29", "29"),
                            ("73", "73"),
                        ],
                        help_text="The category defines what commodities you are applying to import.",
                        max_length=2,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "cp_total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Please note that maximum allocations apply. Please check the guidance to ensure that you do not apply for more than is allowable.",
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(limit_value=0.0)],
                        verbose_name="Total Quantity",
                    ),
                ),
                (
                    "cp_total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value of processing of the fabric/yarn",
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(limit_value=0.0)],
                        verbose_name="Total Value (Euro)",
                    ),
                ),
                (
                    "fq_similar_to_own_factory",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("n/a", "N/A")],
                        help_text="This question only needs to be completed once per year. If you have already completed this question on a previous application this year, you may select 'N/A'.",
                        max_length=3,
                        null=True,
                        verbose_name="Do you manufacture goods which are similar to and at the same stage of processing in your own factory within the EU as the products to be re-imported? (Article 2 (2) (a) of Regulation (EC) No. 3036/94)",
                    ),
                ),
                (
                    "fq_manufacturing_within_eu",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("n/a", "N/A")],
                        help_text="This question only needs to be completed once per year. If you have already completed this question on a previous application this year, you may select 'N/A'.",
                        max_length=3,
                        null=True,
                        verbose_name="Are the main manufacturing processes of the similar goods performed in your own factory within the EU (i.e. sewing and assembly or knitting in the case of fully-fashioned garments obtained from yarn)? (Article 2 (2) (a) of Regulation (EC) No. 3036/94)",
                    ),
                ),
                (
                    "fq_maintained_in_eu",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("n/a", "N/A")],
                        help_text="This question only needs to be completed once per year. If you have already completed this question on a previous application this year, you may select 'N/A'.",
                        max_length=3,
                        null=True,
                        verbose_name="Have you maintained your textile manufacturing activity in the EU with respect to the nature of the products and their quantities? (Article 3 (3) of Regulation (EC) No. 3036/94)",
                    ),
                ),
                (
                    "fq_maintained_in_eu_reasons",
                    models.CharField(
                        blank=True,
                        max_length=4000,
                        null=True,
                        verbose_name="If not, please indicate reasons for the above or make reference to past correspondence.",
                    ),
                ),
                (
                    "cp_origin_country",
                    models.ForeignKey(
                        help_text="Select the country that the compensating products originate from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.country",
                        verbose_name="Country Of Origin",
                    ),
                ),
                (
                    "cp_processing_country",
                    models.ForeignKey(
                        help_text="Select the country that the compensating products were processed in.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.country",
                        verbose_name="Country Of Processing",
                    ),
                ),
                (
                    "supporting_documents",
                    models.ManyToManyField(
                        related_name="_outwardprocessingtradeapplication_supporting_documents_+",
                        to="web.File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.importapplication",),
        ),
        migrations.AlterField(
            model_name="importapplicationtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("FA", "Firearms and Ammunition"),
                    ("SAN", "Derogation from Sanctions Import Ban"),
                    ("SAN_ADHOC_TEMP", "Sanctions and Adhoc"),
                    ("WD", "Wood (Quota)"),
                    ("OPT", "Outward Processing Trade"),
                ],
                max_length=70,
            ),
        ),
    ]
