# Generated by Django 5.1.7 on 2025-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0065_nuclearmaterialapplication_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nuclearmaterialapplication",
            name="dates_of_shipment",
        ),
        migrations.AddField(
            model_name="nuclearmaterialapplication",
            name="shipment_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="nuclearmaterialapplication",
            name="shipment_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="nuclearmaterialapplicationgoods",
            name="unlimited_quantity",
            field=models.BooleanField(default=False, verbose_name="Unlimited Quantity"),
        ),
        migrations.AlterField(
            model_name="nuclearmaterialapplication",
            name="intended_use_of_shipment",
            field=models.TextField(default="", verbose_name="Intended end use of Shipment"),
        ),
        migrations.AlterField(
            model_name="nuclearmaterialapplication",
            name="licence_type",
            field=models.CharField(
                choices=[("S", "Single"), ("O", "Open")],
                default="",
                max_length=1,
                verbose_name="Licence Type",
            ),
        ),
        migrations.AlterField(
            model_name="nuclearmaterialapplication",
            name="security_team_contact_information",
            field=models.TextField(
                default="", verbose_name="Contact Information for Security Team"
            ),
        ),
        migrations.AlterField(
            model_name="nuclearmaterialapplicationgoods",
            name="quantity_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="nuclearmaterialapplicationgoods",
            name="quantity_amount_original",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
