# Generated by Django 2.2.4 on 2019-09-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_auto_20190910_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearmsauthority',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='firearmsauthority',
            name='address_entry_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='firearmsauthority',
            name='certificate_type',
            field=models.CharField(choices=[('DEACTIVATED', 'Deactivation Certificate'), ('FIREARMS', 'Firearms Certificate'), ('RFD', 'Registered Firearms Dealer Certificate'), ('SHOTGUN', 'Shotgun Certificate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firearmsauthority',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='firearmsauthority',
            name='issuing_constabulary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.Constabulary'),
        ),
        migrations.AlterField(
            model_name='firearmsauthority',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='section5authority',
            name='address_entry_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
