# Generated by Django 5.1.7 on 2025-03-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0065_nuclearmaterialapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="hmrc_unit_code",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="hmrc_code",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
