# Generated by Django 3.1.8 on 2021-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0066_dflchecklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="importapplication",
            name="issue_paper_licence_only",
            field=models.BooleanField(null=True, verbose_name="Issue paper licence only?"),
        ),
    ]
