# Generated by Django 2.2.4 on 2019-09-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_auto_20190910_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
        migrations.DeleteModel(
            name='OutboundEmail',
        ),
    ]
