# Generated by Django 5.1.8 on 2025-04-10 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0067_nuclear_materials_email_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECILUserExportApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("cfs", "Certificate of Free Sale (CFS)"),
                            ("com", "Certificate of Manufacture (CoM)"),
                            ("gmp", "Certificate of Good Manufacturing Practice (CGMP)"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="web.exporter",
                    ),
                ),
                (
                    "agent_office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="web.office",
                    ),
                ),
                (
                    "created_by",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="web.exporter",
                    ),
                ),
                (
                    "exporter_office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="web.office",
                    ),
                ),
            ],
        ),
    ]
