# Generated by Django 2.2.4 on 2019-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_auto_20190926_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ('-is_active', 'commodity_code')},
        ),
        migrations.AlterModelOptions(
            name='commoditygroup',
            options={'ordering': ('-is_active', 'group_code')},
        ),
        migrations.AlterModelOptions(
            name='constabulary',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='exporter',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='importer',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='productlegislation',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-is_active', 'template_name')},
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('NEW', 'New'), ('BLOCKED', 'Blocked'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active')], default='NEW', max_length=20),
        ),
    ]
