# Generated by Django 2.2.4 on 2019-10-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20191014_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obsoletecalibregroup',
            options={'ordering': ('-is_active', 'order')},
        ),
    ]
