# Generated by Django 5.1.8 on 2025-04-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0068_eciluserexportapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="address_6",
        ),
        migrations.RemoveField(
            model_name="office",
            name="address_7",
        ),
        migrations.RemoveField(
            model_name="office",
            name="address_8",
        ),
    ]
