# Generated by Django 2.2.4 on 2019-10-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_auto_20191024_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importapplicationtype',
            options={'ordering': ('type', 'sub_type')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_active', 'first_name')},
        ),
        migrations.AddField(
            model_name='importapplication',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_import_applications', to='web.Importer'),
        ),
        migrations.AddField(
            model_name='importapplication',
            name='agent_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_office_import_applications', to='web.Office'),
        ),
    ]
