# Generated by Django 5.1.8 on 2025-04-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0069_remove_office_address_6_remove_office_address_7_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="silapplication",
            name="section_ni",
            field=models.BooleanField(
                default=False, verbose_name="Movements into Northern Ireland"
            ),
        ),
        migrations.CreateModel(
            name="SILGoodsSectionNI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="You no longer need to type the part of the Firearms Act that applies to the item listed in this box. You must select it from the 'Licence for' section.",
                        max_length=4096,
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(help_text="Enter a whole number")),
                ("description_original", models.CharField(max_length=4096)),
                ("quantity_original", models.PositiveBigIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "import_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_section_ni",
                        to="web.silapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
