# Generated by Django 2.2.4 on 2019-10-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_auto_20191024_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_active', 'first_name')},
        ),
    ]
