# Generated by Django 5.1.8 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0069_remove_office_address_6_remove_office_address_7_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfsschedule",
            name="product_standard",
            field=models.CharField(
                choices=[
                    (
                        "PRODUCT_SOLD_ON_UK_MARKET",
                        "It meets safety standards and is currently being sold on the UK market",
                    ),
                    (
                        "PRODUCT_FUTURE_UK_MARKET",
                        "It meets safety standards and will be sold on the UK market in the future",
                    ),
                    ("PRODUCT_EXPORT_ONLY", "It meets safety standards and is for export only"),
                ],
                default="",
                help_text="Products must meet the safety standards to be sold on the UK market",
                max_length=30,
                verbose_name="Which statement applies to the product?",
            ),
        ),
        migrations.AddField(
            model_name="cfsscheduletemplate",
            name="product_standard",
            field=models.CharField(
                choices=[
                    (
                        "PRODUCT_SOLD_ON_UK_MARKET",
                        "It meets safety standards and is currently being sold on the UK market",
                    ),
                    (
                        "PRODUCT_FUTURE_UK_MARKET",
                        "It meets safety standards and will be sold on the UK market in the future",
                    ),
                    ("PRODUCT_EXPORT_ONLY", "It meets safety standards and is for export only"),
                ],
                default="",
                help_text="Products must meet the safety standards to be sold on the UK market",
                max_length=30,
                verbose_name="Which statement applies to the product?",
            ),
        ),
    ]
