# Generated by Django 3.1.9 on 2021-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0069_optchecklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prefix", models.CharField(max_length=8)),
                ("year", models.IntegerField(null=True)),
                ("reference", models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="casereference",
            constraint=models.UniqueConstraint(
                fields=("prefix", "year", "reference"), name="reference_unique"
            ),
        ),
    ]
