# Generated by Django 5.1.9 on 2025-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0070_cfsschedule_product_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfsproduct",
            name="is_raw_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cfsproduct",
            name="product_end_use",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="cfsproducttemplate",
            name="is_raw_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cfsproducttemplate",
            name="product_end_use",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
