# Generated by Django 3.1.12 on 2021-07-01 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0070_casereference"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextilesApplication",
            fields=[
                (
                    "importapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.importapplication",
                    ),
                ),
                (
                    "goods_cleared",
                    models.BooleanField(
                        help_text="If yes, a paper licence will be issued.",
                        null=True,
                        verbose_name="Will the goods be cleared in another Member State of the European Union?",
                    ),
                ),
                (
                    "shipping_year",
                    models.PositiveSmallIntegerField(
                        help_text="Date of shipment should be as shown on your export licence or other export document issued by the exporting country for goods covered by this application. The goods must be exported by 31 December. Shipment is considered to have taken place when the goods are loaded onto the exporting aircraft, vehicle or vessel.",
                        null=True,
                        verbose_name="Shipping Year",
                    ),
                ),
                (
                    "goods_description",
                    models.CharField(
                        help_text="Please describe the goods in no more than five (5) words.",
                        max_length=100,
                        null=True,
                        verbose_name="Goods Description",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Please note that maximum allocations apply. Please check the guidance to ensure that you do not apply for more than is allowable.",
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(limit_value=0.0)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "category_commodity_group",
                    models.ForeignKey(
                        help_text="The category defines what commodities you are applying to import.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.commoditygroup",
                        verbose_name="Category",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        help_text="It is the responsibility of the applicant to ensure that the commodity code in this box is correct. If you are unsure of the correct commodity code, consult the HM Revenue and Customs Integrated Tariff Book, Volume 2, which is available from the Stationery Office. If you are still in doubt, contact the Classification Advisory Service on (01702) 366077.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.commodity",
                        verbose_name="Commodity Code",
                    ),
                ),
                (
                    "category_licence_description",
                    models.CharField(
                        null=True,
                        max_length=4000,
                        verbose_name="Category Description",
                        help_text="By default, this is the category description. You may need to alter the description to a shorter form in order for it to display correctly on the licence.",
                    ),
                ),
                (
                    "supporting_documents",
                    models.ManyToManyField(
                        related_name="_textilesapplication_supporting_documents_+", to="web.File"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.importapplication",),
        ),
    ]
