# Generated by Django 2.2.4 on 2019-11-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20191031_1429'),
        ('web', '0070_auto_20191029_1534'),
    ]

    operations = [
    ]
