# Generated by Django 2.2.4 on 2019-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20191031_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constabularyemail',
            name='email_body',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='constabularyemail',
            name='email_response',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
