# Generated by Django 2.2.4 on 2019-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_merge_20191104_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_complete',
        ),
    ]
