# Generated by Django 3.1.12 on 2021-07-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0073_textileschecklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateOfFreeSaleApplication",
            fields=[
                (
                    "exportapplication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.exportapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("web.exportapplication",),
        ),
    ]
