# Generated by Django 2.2.4 on 2019-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unsuccessful_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
