# # Generated by Django 3.1.8 on 2021-04-27 11:54
#
from django.db import migrations

from .data_migrations.commodity_group_usage import CommodityUsageDataLoader


def add_usage_data(apps, schema_editor):
    Usage = apps.get_model("web", "Usage")
    ImportApplicationType = apps.get_model("web", "ImportApplicationType")
    Country = apps.get_model("web", "Country")
    CommodityGroup = apps.get_model("web", "CommodityGroup")

    loader = CommodityUsageDataLoader(
        usage=Usage,
        import_application_type=ImportApplicationType,
        country=Country,
        commodity_group=CommodityGroup,
    )
    loader.create_usage_records()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0074_certificateoffreesaleapplication"),
    ]

    operations = [
        migrations.RunPython(add_usage_data),
    ]
