# Generated by Django 2.2.4 on 2019-11-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_user_unsuccessful_login_attempts'),
        ('web', '0072_auto_20191106_1116'),
    ]

    operations = [
    ]
