# Generated by Django 2.2.10 on 2020-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_auto_20200210_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtherinformationrequest',
            name='files',
            field=models.ManyToManyField(blank=True, to='web.File'),
        ),
    ]
