# Generated by Django 2.2.10 on 2020-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0079_auto_20200306_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailshot',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='submit_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mailshot',
            name='is_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('NEW', 'New'), ('BLOCKED', 'Blocked'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
