# Generated by Django 2.2.10 on 2020-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_auto_20200330_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailshot',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='mailshot',
            name='is_retraction_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailshot',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailshot',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
