# Generated by Django 2.2.10 on 2020-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_auto_20200331_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailshot',
            name='is_retraction_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('ENDORSEMENT', 'Endorsement'), ('LETTER_TEMPLATE', 'Letter template'), ('EMAIL_TEMPLATE', 'Email template'), ('CFS_TRANSLATION', 'CFS translation'), ('DECLARATION', 'Declaration'), ('CFS_SCHEDULE', 'CFS schedule'), ('LETTER_FRAGMENT', 'Letter fragment'), ('CFS_DECLARATION_TRANSLATION', 'CFS declaration translation'), ('CFS_SCHEDULE_TRANSLATION', 'CFS schedule translation')], max_length=50),
        ),
    ]
