# Generated by Django 2.2.10 on 2020-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0082_auto_20200407_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
