# Generated by Django 2.2.10 on 2020-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_auto_20200417_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='countries',
            field=models.ManyToManyField(to='web.Country'),
        ),
        migrations.AddField(
            model_name='template',
            name='country_translation_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.CountryTranslationSet'),
        ),
        migrations.CreateModel(
            name='CFSScheduleTranslationParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='web.Template')),
            ],
        ),
    ]
