# Generated by Django 2.2.10 on 2020-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_auto_20200420_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfsscheduletranslationparagraph',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='cfsscheduletranslationparagraph',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
