# Generated by Django 2.2.10 on 2020-04-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0009_merge'),
        ('web', '0085_auto_20200420_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('COMPLETED', 'COMPLETED')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalRequestProcess',
            fields=[
                ('subprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Subprocess')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ApprovalRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.subprocess',),
        ),
    ]
