# Generated by Django 2.2.10 on 2020-05-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0086_auto_20200423_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequestprocess',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvalrequestprocess',
            name='approval_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.ApprovalRequest'),
        ),
    ]
