# Generated by Django 2.2.10 on 2020-05-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_auto_20200501_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequestprocess',
            name='restart_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessrequestprocess',
            name='access_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.AccessRequest'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='access_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='web.AccessRequest'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20, null=True),
        ),
    ]
