# Generated by Django 2.2.10 on 2020-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_auto_20200504_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ('-request_date',)},
        ),
        migrations.AlterModelOptions(
            name='obsoletecalibregroup',
            options={'ordering': ('order', '-is_active')},
        ),
    ]
