# Generated by Django 2.2.10 on 2020-05-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0089_auto_20200512_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obsoletecalibregroup',
            options={'ordering': ('order', '-is_active')},
        ),
    ]
