# Generated by Django 2.2.10 on 2020-05-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0090_auto_20200513_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrytranslationset',
            options={'ordering': ('-is_active', 'name')},
        ),
    ]
