# Generated by Django 2.2.10 on 2020-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_auto_20200519_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], max_length=20, null=True),
        ),
    ]
