export_case_note_1 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>1</NOTE_ID>
    <STATUS>DRAFT</STATUS>
    <BODY>This is a case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>1</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>4</NOTE_ID>
    <STATUS>DELETED</STATUS>
    <BODY>This is a deleted case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-20T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>4</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""


export_case_note_2 = """
<NOTE_LIST>
  <NOTE>
    <NOTE_ID>2</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is another case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>2</FOLDER_ID>
  </NOTE>
  <NOTE>
    <NOTE_ID>3</NOTE_ID>
    <STATUS>COMPLETED</STATUS>
    <BODY>This is a third case note</BODY>
    <CREATE>
      <CREATED_DATETIME>2022-09-20T08:31:34</CREATED_DATETIME>
      <CREATED_BY_WUA_ID>2</CREATED_BY_WUA_ID>
    </CREATE>
    <LAST_UPDATE>
      <LAST_UPDATED_DATETIME>2022-09-21T08:31:34</LAST_UPDATED_DATETIME>
      <LAST_UPDATED_BY_WUA_ID>2</LAST_UPDATED_BY_WUA_ID>
    </LAST_UPDATE>
    <FOLDER_ID>3</FOLDER_ID>
  </NOTE>
</NOTE_LIST>
"""
