cfs_product = """
<PRODUCT_LIST>
  <PRODUCT>
    <NAME>Product A</NAME>
  </PRODUCT>
  <PRODUCT>
    <NAME>Product B</NAME>
  </PRODUCT>
  <PRODUCT>
    <NAME>Product C</NAME>
  </PRODUCT>
  <PRODUCT>
    <NAME />
  </PRODUCT>
</PRODUCT_LIST>
"""

cfs_product_biocide = """
<PRODUCT_LIST>
  <PRODUCT>
    <NAME>Product A</NAME>
    <PRODUCT_TYPE_NUMBER_LIST>
      <PRODUCT_TYPE_NUMBER>
        <NUMBER>1</NUMBER>
        <ACTIONS />
      </PRODUCT_TYPE_NUMBER>
      <PRODUCT_TYPE_NUMBER>
        <NUMBER>2</NUMBER>
        <ACTIONS />
      </PRODUCT_TYPE_NUMBER>
    </PRODUCT_TYPE_NUMBER_LIST>
    <ACTIVE_INGREDIENT_LIST>
      <ACTIVE_INGREDIENT>
        <NAME>AI 1</NAME>
        <CAS_NUMBER>12-34-5</CAS_NUMBER>
        <ACTIONS />
      </ACTIVE_INGREDIENT>
      <ACTIVE_INGREDIENT>
        <NAME>AI 2</NAME>
        <CAS_NUMBER>22-34-5</CAS_NUMBER>
        <ACTIONS />
      </ACTIVE_INGREDIENT>
    </ACTIVE_INGREDIENT_LIST>
    <CHEMICAL_NAME />
    <MANUFACTURING_PROCESS />
    <IS_BIOCIDAL_FLAG />
  </PRODUCT>
  <PRODUCT>
    <NAME>Product B</NAME>
    <PRODUCT_TYPE_NUMBER_LIST>
      <PRODUCT_TYPE_NUMBER>
        <NUMBER>3</NUMBER>
        <ACTIONS />
      </PRODUCT_TYPE_NUMBER>
      <PRODUCT_TYPE_NUMBER />
    </PRODUCT_TYPE_NUMBER_LIST>
    <ACTIVE_INGREDIENT_LIST>
      <ACTIVE_INGREDIENT>
        <NAME>AI 3</NAME>
        <CAS_NUMBER>32-34-5</CAS_NUMBER>
        <ACTIONS />
      </ACTIVE_INGREDIENT>
      <ACTIVE_INGREDIENT>
        <NAME>AI 4</NAME>
        <CAS_NUMBER />
        <ACTIONS />
      </ACTIVE_INGREDIENT>
      <ACTIVE_INGREDIENT>
        <NAME />
        <CAS_NUMBER>32-34-6</CAS_NUMBER>
        <ACTIONS />
      </ACTIVE_INGREDIENT>
    </ACTIVE_INGREDIENT_LIST>
    <CHEMICAL_NAME />
    <MANUFACTURING_PROCESS />
    <IS_BIOCIDAL_FLAG />
  </PRODUCT>
</PRODUCT_LIST>
"""


cfs_legislation = """
<LEGISLATION_LIST>
  <LEGISLATION>1</LEGISLATION>
  <LEGISLATION>3</LEGISLATION>
</LEGISLATION_LIST>
"""


cfs_legislation_biocide = """
<LEGISLATION_LIST>
  <LEGISLATION>2</LEGISLATION>
</LEGISLATION_LIST>
"""
