# flake8: noqa
import_contact_xml = """
<SELLER_HOLDER_LIST>
  <SELLER_HOLDER>
    <PERSON_DETAILS>
      <PERSON_TYPE>LEGAL_PERSON</PERSON_TYPE>
      <LEGAL_PERSON_NAME>FIREARMS DEALER</LEGAL_PERSON_NAME>
      <REGISTRATION_NUMBER />
      <FIRST_NAME />
      <SURNAME />
    </PERSON_DETAILS>
    <ADDRESS>
      <STREET_AND_NUMBER>123 FAKE ST</STREET_AND_NUMBER>
      <TOWN_CITY>FAKE CITY</TOWN_CITY>
      <POSTCODE />
      <REGION>FAKE REGION</REGION>
      <COUNTRY>1000</COUNTRY>
    </ADDRESS>
    <IS_DEALER_FLAG>Y</IS_DEALER_FLAG>
    <SELLER_HOLDER_ID>1</SELLER_HOLDER_ID>
    <UPDATE_FLAG />
  </SELLER_HOLDER>
  <SELLER_HOLDER>
    <PERSON_DETAILS>
      <PERSON_TYPE>LEGAL_PERSON</PERSON_TYPE>
      <LEGAL_PERSON_NAME>ANOTHER DELEAR</LEGAL_PERSON_NAME>
      <REGISTRATION_NUMBER />
      <FIRST_NAME />
      <SURNAME />
    </PERSON_DETAILS>
    <ADDRESS>
      <STREET_AND_NUMBER>456 FAKE RD</STREET_AND_NUMBER>
      <TOWN_CITY>FAKE TOWN</TOWN_CITY>
      <POSTCODE />
      <REGION>SOUTH FAKE REGION</REGION>
      <COUNTRY>1000</COUNTRY>
    </ADDRESS>
    <IS_DEALER_FLAG>Y</IS_DEALER_FLAG>
    <SELLER_HOLDER_ID>2</SELLER_HOLDER_ID>
    <UPDATE_FLAG />
  </SELLER_HOLDER>
</SELLER_HOLDER_LIST>
""".strip()


sr_upload_xml = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>UPLOAD</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST/>
          <FILE_UPLOAD_LIST>
            <FILE_UPLOAD>
                <FILE_CONTENT>
                  <filename>a file.pdf</filename>
                  <content-type>application/pdf</content-type>
                  <browser-content-type>application/pdf</browser-content-type>
                  <original-file-location>a file.pdf</original-file-location>
                  <size>1234</size>
                  <status>complete</status>
                  <status-message>Upload complete</status-message>
                  <system-message/>
                  <readable-error-message/>
                  <upload-date-time>2021-11-08T08:29:59</upload-date-time>
                  <file-upload-type>file</file-upload-type>
                  <file-id>abcdefg</file-id>
                  <character-encoding>not specified</character-encoding>
                  <diagnostic-info>
                    <filename>a file.pdf</filename>
                    <content-type>application/pdf</content-type>
                    <browser-content-type>application/pdf</browser-content-type>
                    <original-file-location>a file.pdf</original-file-location>
                    <estimated-size>1234</estimated-size>
                    <status>complete</status>
                    <status-message>Upload complete</status-message>
                    <system-message/>
                    <readable-error-message/>
                    <upload-date-time>2021-11-08T08:29:59</upload-date-time>
                    <file-id>abcde</file-id>
                  </diagnostic-info>
                </FILE_CONTENT>
            </FILE_UPLOAD>
          </FILE_UPLOAD_LIST>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT>AIR</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-10-14</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-08T08:31:34</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip()

sr_manual_xml = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>50</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>N/A</SERIAL_NUMBER>
              <CALIBRE>6MM</CALIBRE>
              <MAKE_MODEL>A gun barrel</MAKE_MODEL>
              <PROOFING>N</PROOFING>
            </FIREARMS_DETAILS>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>123456</SERIAL_NUMBER>
              <CALIBRE>.30</CALIBRE>
              <MAKE_MODEL>A gun</MAKE_MODEL>
              <PROOFING>Y</PROOFING>
            </FIREARMS_DETAILS>
          </FIREARMS_DETAILS_LIST>
          <FILE_UPLOAD_LIST/>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT>RAIL</MODE_OF_TRANSPORT>
      <RECEIVED_DATE>2021-11-03</RECEIVED_DATE>
      <REPORT_SELLER_HOLDER>1</REPORT_SELLER_HOLDER>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-11-07T13:41:00</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
  <FA_SUPPLEMENTARY_REPORT>
    <HISTORICAL_REPORT_LIST/>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
              <CALIBRE>mixed</CALIBRE>
              <MAKE_MODEL>Various</MAKE_MODEL>
              <PROOFING>Y</PROOFING>
            </FIREARMS_DETAILS>
          </FIREARMS_DETAILS_LIST>
          <FILE_UPLOAD_LIST/>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT/>
      <RECEIVED_DATE/>
      <REPORT_SELLER_HOLDER/>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>2</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-12-20T10:24:30</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip()


sr_list = """
<FA_SUPPLEMENTARY_REPORT_LIST>
  <FA_SUPPLEMENTARY_REPORT>
      <HISTORICAL_REPORT_LIST/>
    <FA_SUPPLEMENTARY_REPORT_DETAILS>
      <GOODS_LINE_LIST>
        <GOODS_LINE>
          <GOODS_ITEM_DESC>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.</GOODS_ITEM_DESC>
          <GOODS_ITEM_QUANTITY>100</GOODS_ITEM_QUANTITY>
          <GOOD_ITEM_ID>Firearms, component parts thereof, or ammunition of any applicable commodity code, other than those falling under Section 5 of the Firearms Act 1968 as amended.1</GOOD_ITEM_ID>
          <FA_REPORTING_MODE>MANUAL</FA_REPORTING_MODE>
          <FIREARMS_DETAILS_LIST>
            <FIREARMS_DETAILS>
              <SERIAL_NUMBER>Ammunition</SERIAL_NUMBER>
              <CALIBRE>mixed</CALIBRE>
              <MAKE_MODEL>Various</MAKE_MODEL>
              <PROOFING>Y</PROOFING>
            </FIREARMS_DETAILS>
          </FIREARMS_DETAILS_LIST>
          <FILE_UPLOAD_LIST/>
          <GOODS_ITEM_SUBMIT/>
        </GOODS_LINE>
      </GOODS_LINE_LIST>
      <MODE_OF_TRANSPORT/>
      <RECEIVED_DATE/>
      <REPORT_SELLER_HOLDER/>
      <REPORT_SUBMITTED_FLAG>true</REPORT_SUBMITTED_FLAG>
      <SUBMITTED_BY_WUA_ID>1</SUBMITTED_BY_WUA_ID>
      <SUBMITTED_DATETIME>2021-12-20T10:24:30</SUBMITTED_DATETIME>
      <FA_REPORT_ID>1</FA_REPORT_ID>
    </FA_SUPPLEMENTARY_REPORT_DETAILS>
  </FA_SUPPLEMENTARY_REPORT>
</FA_SUPPLEMENTARY_REPORT_LIST>
""".strip()


dfl_goods_cert = """
<FA_GOODS_CERTS>
  <COMMODITY_LIST>
    <COMMODITY>
      <COMMODITY_DESC>Test Commodity A</COMMODITY_DESC>
      <OBSOLETE_CALIBRE />
      <QUANTITY>1</QUANTITY>
      <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
      <QUANTITY_UNLIMITED_FLAG />
      <UNIT>UNITS</UNIT>
    </COMMODITY>
    <COMMODITY>
      <COMMODITY_DESC>Test Commodity B</COMMODITY_DESC>
      <OBSOLETE_CALIBRE />
      <QUANTITY>1</QUANTITY>
      <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
      <QUANTITY_UNLIMITED_FLAG />
      <UNIT>UNITS</UNIT>
    </COMMODITY>
  </COMMODITY_LIST>
  <FIREARMS_CERTIFICATE_LIST>
    <FIREARMS_CERTIFICATE>
      <TARGET_ID>1234</TARGET_ID>
      <CERTIFICATE_REF>REF A</CERTIFICATE_REF>
      <CERTIFICATE_TYPE>DEACTIVATED</CERTIFICATE_TYPE>
      <CONSTABULARY />
      <DATE_ISSUED />
      <EXPIRY_DATE />
      <ISSUING_COUNTRY>1</ISSUING_COUNTRY>
    </FIREARMS_CERTIFICATE>
    <FIREARMS_CERTIFICATE>
      <TARGET_ID>5678</TARGET_ID>
      <CERTIFICATE_REF>REF B</CERTIFICATE_REF>
      <CERTIFICATE_TYPE>DEACTIVATED</CERTIFICATE_TYPE>
      <CONSTABULARY />
      <DATE_ISSUED />
      <EXPIRY_DATE />
      <ISSUING_COUNTRY>2</ISSUING_COUNTRY>
    </FIREARMS_CERTIFICATE>
  </FIREARMS_CERTIFICATE_LIST>
</FA_GOODS_CERTS>
""".strip()

rfd_cert = """
<FIREARMS_CERTIFICATE_LIST>
  <FIREARMS_CERTIFICATE>
    <TARGET_ID>1</TARGET_ID>
    <CERTIFICATE_REF>A REF</CERTIFICATE_REF>
    <CERTIFICATE_TYPE>RFD</CERTIFICATE_TYPE>
    <CONSTABULARY>1</CONSTABULARY>
    <DATE_ISSUED>2020-06-08</DATE_ISSUED>
    <EXPIRY_DATE>2023-06-07</EXPIRY_DATE>
    <ISSUING_COUNTRY />
  </FIREARMS_CERTIFICATE>
""".strip()


sil_goods = """
<COMMODITY_LIST>
  <COMMODITY>
    <SECTION>SEC1</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Gun</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>5</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC2</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Rifle</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>5</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>SEC5</SECTION>
    <SECTION_5_CLAUSE>5_1_ABA</SECTION_5_CLAUSE>
    <COMMODITY_DESC>Test Pistol</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>10</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG>false</QUANTITY_UNLIMITED_FLAG>
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900>N</MANUFACTURED_BEFORE_1900>
    <CURIOSITY_OR_ORNAMENT />
    <CURIOSITY_STATEMENT_AGREED />
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939 />
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OBSOLETE_CALIBRE</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Revolver</COMMODITY_DESC>
    <OBSOLETE_CALIBRE>
      <OC_ID>444</OC_ID>
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
    <QUANTITY>1</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG />
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900 />
    <CURIOSITY_OR_ORNAMENT>Y</CURIOSITY_OR_ORNAMENT>
    <CURIOSITY_STATEMENT_AGREED>true</CURIOSITY_STATEMENT_AGREED>
    <BREECH_LOADING_CENTREFIRE>Y</BREECH_LOADING_CENTREFIRE>
    <MANUFACTURED_AFTER_1899_BEFORE_1939>Y</MANUFACTURED_AFTER_1899_BEFORE_1939>
    <ORIGINAL_CHAMBERING>Y</ORIGINAL_CHAMBERING>
    <MUZZLE_LOADING />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE />
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED />
    <OTHER_IGNITION_SYSTEM />
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE />
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT></S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
  </COMMODITY>
  <COMMODITY>
    <SECTION>OTHER</SECTION>
    <SECTION_5_CLAUSE />
    <COMMODITY_DESC>Test Other</COMMODITY_DESC>
    <QUANTITY>1</QUANTITY>
    <QUANTITY_UNLIMITED>Unlimited</QUANTITY_UNLIMITED>
    <QUANTITY_UNLIMITED_FLAG />
    <UNIT>UNITS</UNIT>
    <MANUFACTURED_BEFORE_1900 />
    <CURIOSITY_OR_ORNAMENT>Y</CURIOSITY_OR_ORNAMENT>
    <CURIOSITY_STATEMENT_AGREED>true</CURIOSITY_STATEMENT_AGREED>
    <BREECH_LOADING_CENTREFIRE />
    <MANUFACTURED_AFTER_1899_BEFORE_1939>Y</MANUFACTURED_AFTER_1899_BEFORE_1939>
    <ORIGINAL_CHAMBERING />
    <MUZZLE_LOADING>N</MUZZLE_LOADING>
    <OTHER_BREECH_RIMFIRE_CARTRIDGE>Y</OTHER_BREECH_RIMFIRE_CARTRIDGE>
    <OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED>.32 rimfire</OTHER_BREECH_RIMFIRE_CARTRIDGE_SPECIFIED>
    <OTHER_IGNITION_SYSTEM>N</OTHER_IGNITION_SYSTEM>
    <OTHER_IGNITION_SYSTEM_SPECIFIED />
    <OTHER_IGNITION_SYSTEM_SPECIFIED_OTHER />
    <SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES>N</SHOTGUN_PUNTGUN_RIFLE_LISTED_CARTRIDGES>
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE>N</SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE>
    <SHOTGUN_PUNTGUN_RIFLE_OVER_10_BORE_SPECIFIED />
    <OTHER_OPTIONS_ERROR></OTHER_OPTIONS_ERROR>
    <S58_2_YES_ANSWER_COUNT>1.0</S58_2_YES_ANSWER_COUNT>
    <OBSOLETE_CALIBRE_SELECTED></OBSOLETE_CALIBRE_SELECTED>
    <OBSOLETE_CALIBRE>
      <OC_ID />
      <NA_FLAG>false</NA_FLAG>
    </OBSOLETE_CALIBRE>
  </COMMODITY>
</COMMODITY_LIST>
""".strip()
