opt_commodities = """
<COMMODITY_LIST>
  <COMMODITY>
    <COMMODITY_ID>1</COMMODITY_ID>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>2</COMMODITY_ID>
  </COMMODITY>
  <COMMODITY>
    <COMMODITY_ID>3</COMMODITY_ID>
  </COMMODITY>
</COMMODITY_LIST>
"""
