def get():
    return (
        (None, ""),
        ("Afghanistan", "Afghanistan"),
        ("Albania", "Albania"),
        ("Algeria", "Algeria"),
        ("Angola", "Angola"),
        ("Any Country", "Any Country"),
        ("Any EU Country", "Any EU Country"),
        ("Any Non EU Country", "Any Non EU Country"),
        ("Argentina", "Argentina"),
        ("Armenia", "Armenia"),
        ("Australia", "Australia"),
        ("Austria", "Austria"),
        ("Azerbaijan", "Azerbaijan"),
        ("Bahamas", "Bahamas"),
        ("Bahrain", "Bahrain"),
        ("Bangladesh", "Bangladesh"),
        ("Barbados", "Barbados"),
        ("Belarus", "Belarus"),
        ("Belgium", "Belgium"),
        ("Bermuda", "Bermuda"),
        ("Bhutan", "Bhutan"),
        ("Bolivia", "Bolivia"),
        ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
        ("Botswana", "Botswana"),
        ("Brazil", "Brazil"),
        ("British Virgin Islands", "British Virgin Islands"),
        ("Brunei", "Brunei"),
        ("Bulgaria", "Bulgaria"),
        ("Burma (Myanamar)", "Burma (Myanamar)"),
        ("Cambodia", "Cambodia"),
        ("Canada", "Canada"),
        ("Chile", "Chile"),
        ("China", "China"),
        ("Colombia", "Colombia"),
        ("Congo", "Congo"),
        ("Congo (Dem. Republic)", "Congo (Dem. Republic)"),
        ("Costa Rica", "Costa Rica"),
        ("Cote d'Ivoire ", "Cote d'Ivoire "),
        ("Croatia", "Croatia"),
        ("Cuba", "Cuba"),
        ("Cyprus", "Cyprus"),
        ("Denmark", "Denmark"),
        ("Dominica", "Dominica"),
        ("Dominican Republic", "Dominican Republic"),
        ("Ecuador", "Ecuador"),
        ("Egypt", "Egypt"),
        ("El Salvador", "El Salvador"),
        ("Equatorial Guinea", "Equatorial Guinea"),
        ("Estonia", "Estonia"),
        ("Ethiopia", "Ethiopia"),
        ("European Union", "European Union"),
        ("Falkland Islands", "Falkland Islands"),
        ("Faroe Islands", "Faroe Islands"),
        ("Finland", "Finland"),
        ("France", "France"),
        ("Gabon", "Gabon"),
        ("Gambia", "Gambia"),
        ("Georgia", "Georgia"),
        ("Germany", "Germany"),
        ("Ghana", "Ghana"),
        ("Gibraltar", "Gibraltar"),
        ("Greece", "Greece"),
        ("Greenland", "Greenland"),
        ("Guatemala", "Guatemala"),
        ("Guernsey", "Guernsey"),
        ("Guinea", "Guinea"),
        ("Haiti", "Haiti"),
        ("Honduras", "Honduras"),
        ("Hong Kong", "Hong Kong"),
        ("Hungary", "Hungary"),
        ("Iceland", "Iceland"),
        ("India", "India"),
        ("Indonesia", "Indonesia"),
        ("Iran", "Iran"),
        ("Iraq", "Iraq"),
        ("Irish Republic", "Irish Republic"),
        ("Israel", "Israel"),
        ("Italy", "Italy"),
        ("Jamaica", "Jamaica"),
        ("Japan", "Japan"),
        ("Jersey", "Jersey"),
        ("Jordan", "Jordan"),
        ("Kazakhstan", "Kazakhstan"),
        ("Kenya", "Kenya"),
        ("Korea (North)", "Korea (North)"),
        ("Korea (South)", "Korea (South)"),
        ("Kosovo", "Kosovo"),
        ("Kuwait", "Kuwait"),
        ("Kyrgyzstan", "Kyrgyzstan"),
        ("Laos", "Laos"),
        ("Latvia", "Latvia"),
        ("Lebanon", "Lebanon"),
        ("Libya", "Libya"),
        ("Liechtenstein", "Liechtenstein"),
        ("Lithuania", "Lithuania"),
        ("Luxembourg", "Luxembourg"),
        ("Macao", "Macao"),
        ("Macedonia, Former Yugoslav Republic of",
         "Macedonia, Former Yugoslav Republic of"),
        ("Madagascar", "Madagascar"),
        ("Malaysia", "Malaysia"),
        ("Malta", "Malta"),
        ("Mauritania", "Mauritania"),
        ("Mauritius", "Mauritius"),
        ("Mexico", "Mexico"),
        ("Micronesia", "Micronesia"),
        ("Moldova", "Moldova"),
        ("Mongolia", "Mongolia"),
        ("Montenegro", "Montenegro"),
        ("Morocco", "Morocco"),
        ("Mozambique", "Mozambique"),
        ("Namibia", "Namibia"),
        ("Nauru", "Nauru"),
        ("Nepal", "Nepal"),
        ("Netherlands", "Netherlands"),
        ("New Zealand", "New Zealand"),
        ("Nicaragua", "Nicaragua"),
        ("Nigeria", "Nigeria"),
        ("Norway", "Norway"),
        ("Occupied Palestinian Territories",
         "Occupied Palestinian Territories"),
        ("Oman", "Oman"),
        ("Pakistan", "Pakistan"),
        ("Panama", "Panama"),
        ("Paraguay", "Paraguay"),
        ("Peru", "Peru"),
        ("Philippines", "Philippines"),
        ("Poland", "Poland"),
        ("Portugal", "Portugal"),
        ("Puerto Rico", "Puerto Rico"),
        ("Qatar", "Qatar"),
        ("Romania", "Romania"),
        ("Russian Federation", "Russian Federation"),
        ("Saint Helena", "Saint Helena"),
        ("Saudi Arabia", "Saudi Arabia"),
        ("Serbia", "Serbia"),
        ("Singapore", "Singapore"),
        ("Slovenia", "Slovenia"),
        ("Soloman Islands", "Soloman Islands"),
        ("Somalia", "Somalia"),
        ("South Africa", "South Africa"),
        ("Spain", "Spain"),
        ("Sri Lanka", "Sri Lanka"),
        ("Sudan", "Sudan"),
        ("Swaziland", "Swaziland"),
        ("Sweden", "Sweden"),
        ("Switzerland", "Switzerland"),
        ("Syria", "Syria"),
        ("Taiwan", "Taiwan"),
        ("Tajikistan", "Tajikistan"),
        ("Tanzania", "Tanzania"),
        ("Thailand", "Thailand"),
        ("Trinidad &amp; Tobago", "Trinidad &amp; Tobago"),
        ("Tunisia", "Tunisia"),
        ("Turkey", "Turkey"),
        ("Turkmenistan", "Turkmenistan"),
        ("USA", "USA"),
        ("Ukraine", "Ukraine"),
        ("United Arab Emirates", "United Arab Emirates"),
        ("United Kingdom", "United Kingdom"),
        ("Uruguay", "Uruguay"),
        ("Uzbekistan", "Uzbekistan"),
        ("Venezuela", "Venezuela"),
        ("Vietnam", "Vietnam"),
        ("Yemen", "Yemen"),
        ("Zimbabwe", "Zimbabwe"),
        ("the Czech Republic", "the Czech Republic"),
        ("the Slovak Republic", "the Slovak Republic"),
    )
