SELECT
  rt.RES_TYPE
  ,rtr.role_name
  ,rtp.DEFAULT_SYSTEM_PRIV
  FROM
	  XVIEWMGR.XVIEW_RESOURCE_TYPES rt
	,XVIEWMGR.XVIEW_RESOURCE_TYPE_ROLES rtr
	,XVIEWMGR.XVIEW_RESOURCE_TYPE_PRIVS rtp
 WHERE
	rt.res_type = rtr.res_type
AND rt.SCOPED_WITHIN='UNIVERSAL_SET'
AND rtr.RES_TYPE=rtp.RES_TYPE(+)
AND rtr.ROLE_NAME=rtp.ROLE_NAME(+)
  --AND rtr.RES_TYPE='COUNTRY_SUPER_USERS'
 ORDER BY rt.RES_TYPE, rtr.ROLE_NAME
