import datetime as dt

from web.models import ImportApplicationType, Usage

START_DATE = dt.date(2023, 1, 1)


def add_usage_data():
    adhoc_id = ImportApplicationType.objects.get(type=ImportApplicationType.Types.SANCTION_ADHOC).id
    opt_id = ImportApplicationType.objects.get(type=ImportApplicationType.Types.OPT).id
    tex_id = ImportApplicationType.objects.get(type=ImportApplicationType.Types.TEXTILES).id

    Usage.objects.bulk_create(
        [
            Usage(**u)
            for u in [
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 234,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 200,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 95,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 95,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 198,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 243,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 198,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 246,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 246,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 131,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 39,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 131,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 145,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 39,
                    "commodity_group_id": 242,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 251,
                    "start_date": dt.date(2024, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 237,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 237,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 200,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 200,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 252,
                    "start_date": dt.date(2024, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 198,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 200,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 214,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 214,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 95,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 231,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 236,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 236,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 214,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 229,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 241,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 244,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 95,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 160,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 246,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 248,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 215,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 220,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 216,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 216,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 215,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 149,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 141,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 245,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": opt_id,
                    "country_id": 16,
                    "commodity_group_id": 159,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 247,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 221,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 249,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 249,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 249,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 253,
                    "start_date": dt.date(2024, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 214,
                    "start_date": dt.date(2021, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 237,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 219,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 225,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 224,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 237,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 225,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 232,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 226,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 232,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 217,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 16,
                    "commodity_group_id": 226,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 236,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 237,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 238,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 238,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 235,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 200,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": tex_id,
                    "country_id": 79,
                    "commodity_group_id": 198,
                    "start_date": dt.date(2013, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 240,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 240,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 240,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 218,
                    "start_date": dt.date(2022, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 250,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
                {
                    "application_type_id": adhoc_id,
                    "country_id": 122,
                    "commodity_group_id": 240,
                    "start_date": dt.date(2023, 1, 1),
                    "end_date": None,
                    "maximum_allocation": None,
                },
            ]
        ]
    )
