#!/bin/bash

set -e

echo "Delete local S3 Cache"
make clean_local_buckets

echo "Stop all running containers"
make down

echo "Starting localstack"
make localstack

echo "Delete docker volumes"
docker volume rm icms_pgdata icms_redis_data

echo "Starting web (and related) containers"
docker compose up -d web

echo "Running migrations"
docker compose exec web python ./manage.py migrate

echo "Create local S3 buckets"
make local_s3

echo "Adding dummy data"
docker compose exec web python ./manage.py add_dummy_data --password admin

echo "Restarting containers in the background"
make debug

echo "collecting static content"
make collectstatic
