from .base import BaseResultsSerializer, BaseSerializer, MetadataListSerializer
from .export_application import (
    CFSProductListSerializer,
    CFSProductSerializer,
    CFSScheduleListSerializer,
    CFSScheduleSerializer,
    COMApplicationListSerializer,
    COMApplicationSerializer,
    ExportApplicationListSerializer,
    ExportApplicationSerializer,
    ExportCertificateDocumentSerializer,
    ExportDocumentListSerializer,
    GMPApplicationListSerializer,
    GMPApplicationSerializer,
    LegislationListSerializer,
    LegislationSerializer,
)
from .import_application import (
    ImportApplicationListSerializer,
    ImportApplicationSerializer,
    ImportLicenceDocumentListSerializer,
    ImportLicenceDocumentSerializer,
)
from .user import (
    ExporterListSerializer,
    ExporterSerializer,
    ImporterListSerializer,
    ImporterSerializer,
    OfficeListSerializer,
    OfficeSerializer,
    UserFeedbackSurveys,
    UserFeedbackSurveySerializer,
    UserListSerializer,
    UserSerializer,
)

# Used to determine which tables get listed on the table-metadata data workspace api
DATA_SERIALIZERS: list[type[BaseSerializer]] = [
    CFSProductSerializer,
    CFSScheduleSerializer,
    COMApplicationSerializer,
    ExportApplicationSerializer,
    ExportCertificateDocumentSerializer,
    ExporterSerializer,
    GMPApplicationSerializer,
    ImportApplicationSerializer,
    ImportLicenceDocumentSerializer,
    ImporterSerializer,
    LegislationSerializer,
    OfficeSerializer,
    UserFeedbackSurveySerializer,
    UserSerializer,
]

__all__ = [
    "BaseResultsSerializer",
    "BaseSerializer",
    "CaseDocumentListSerializer",
    "CaseDocumentSerializer",
    "CFSProductListSerializer",
    "CFSProductSerializer",
    "CFSScheduleListSerializer",
    "CFSScheduleSerializer",
    "COMApplicationListSerializer",
    "COMApplicationSerializer",
    "ExportApplicationListSerializer",
    "ExportApplicationSerializer",
    "ExportCertificateDocumentSerializer",
    "ExportDocumentListSerializer",
    "ExporterListSerializer",
    "ExporterSerializer",
    "GMPApplicationListSerializer",
    "GMPApplicationSerializer",
    "ImportApplicationListSerializer",
    "ImportApplicationSerializer",
    "ImportLicenceDocumentListSerializer",
    "ImportLicenceDocumentSerializer",
    "ImporterListSerializer",
    "ImporterSerializer",
    "LegislationListSerializer",
    "LegislationSerializer",
    "MetadataListSerializer",
    "OfficeListSerializer",
    "OfficeSerializer",
    "UserFeedbackSurveySerializer",
    "UserFeedbackSurveys",
    "UserListSerializer",
    "UserSerializer",
]
