from web.domains.case._import.models import *  # NOQA
from web.domains.case.access.models import *  # NOQA
from web.domains.case.export.models import *  # NOQA
from web.domains.case.fir.models import *  # NOQA
from web.domains.case.models import *  # NOQA
from web.domains.commodity.models import *  # NOQA
from web.domains.constabulary.models import *  # NOQA
from web.domains.country.models import *  # NOQA
from web.domains.exporter.models import *  # NOQA
from web.domains.file.models import *  # NOQA
from web.domains.firearms.models import *  # NOQA
from web.domains.importer.models import *  # NOQA
from web.domains.legislation.models import *  # NOQA
from web.domains.mailshot.models import *  # NOQA
from web.domains.office.models import *  # NOQA
from web.domains.template.models import *  # NOQA
from web.domains.user.models import *  # NOQA
from web.permissions import *  # NOQA
